/* ===== Observatorio EV · v3 (tabs + filtros + mapas) ===== */
let DB=null,CARG=null,COORDS=null,REP=null;
const DATA={}, F={}, TAB={};
let _charts=[], _maps=[];
const fmt=n=>(Math.round((n||0)*10)/10).toLocaleString('es-CL');
const fint=n=>Math.round(n||0).toLocaleString('es-CL');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const norm=s=>(s||'').toString().toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'').trim();
const V='1781969681';
async function load(n){if(DATA[n])return DATA[n];DATA[n]=await fetch(`data/${n}.json?v=${V}`).then(r=>r.json());return DATA[n];}
function killViz(){_charts.forEach(c=>{try{c.destroy()}catch(e){}});_charts=[];_maps.forEach(m=>{try{m.remove()}catch(e){}});_maps=[];}
function chart(ctx,cfg){const c=new Chart(ctx,cfg);_charts.push(c);return c;}
function leaflet(id,view){const m=L.map(id,{scrollWheelZoom:false}).setView(view||[-35.5,-71.3],5);
  L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{maxZoom:18,attribution:'© OpenStreetMap, © CARTO'}).addTo(m);_maps.push(m);return m;}
const datechip=()=>`<span class="datechip">📅 ${DB.fecha}</span>`;
function spark(serie,color){if(!serie||serie.length<2)return'';const w=120,h=34,mn=Math.min(...serie),mx=Math.max(...serie),rg=(mx-mn)||1;
  const pts=serie.map((v,i)=>[i/(serie.length-1)*w,h-((v-mn)/rg)*(h-6)-3]);
  const dd=pts.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+' '+p[1].toFixed(1)).join(' ');const id='g'+Math.random().toString(36).slice(2,7);
  return `<svg class="spark" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><defs><linearGradient id="${id}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${color}" stop-opacity=".25"/><stop offset="1" stop-color="${color}" stop-opacity="0"/></linearGradient></defs><path d="${dd} L${w} ${h} L0 ${h} Z" fill="url(#${id})"/><path d="${dd}" fill="none" stroke="${color}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><circle cx="${pts.at(-1)[0].toFixed(1)}" cy="${pts.at(-1)[1].toFixed(1)}" r="3" fill="${color}"/></svg>`;}
function kpi(o){return `<div class="kpi"><div class="top"><div class="ico" style="background:${o.bg};color:${o.c}">${o.icon}</div><div class="lbl">${o.lbl}</div></div><div class="val">${o.val}${o.unit?`<small>${o.unit}</small>`:''}</div>${o.serie?spark(o.serie,o.c):''}</div>`;}
const IC={bolt:'<svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M13 2L3 14h7l-1 8 10-12h-7z"/></svg>',car:'<svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M5 11l1.5-4.5h11L19 11m-1.5 5a1.5 1.5 0 110-3 1.5 1.5 0 010 3m-11 0a1.5 1.5 0 110-3 1.5 1.5 0 010 3M19 6.5A1.5 1.5 0 0017.5 5h-11A1.5 1.5 0 005 6.5L3 12v8h2v-2h14v2h2v-8z"/></svg>',plug:'<svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M7 2v6m10-6v6M5 8h14v2a7 7 0 01-6 6.9V22h-2v-5.1A7 7 0 015 10z"/></svg>',map:'<svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2a7 7 0 00-7 7c0 5 7 13 7 13s7-8 7-13a7 7 0 00-7-7m0 9.5A2.5 2.5 0 1112 6a2.5 2.5 0 010 5.5"/></svg>',sun:'<svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M12 7a5 5 0 100 10 5 5 0 000-10m0-5v3m0 14v3M2 12h3m14 0h3M4.2 4.2l2.1 2.1m11.4 11.4l2.1 2.1M4.2 19.8l2.1-2.1M17.7 6.3l2.1-2.1"/></svg>',bat:'<svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M4 8h14v8H4zm15 2h2v4h-2M7 10l3 0-1 2 2 0-3 4 1-3-2 0z"/></svg>',target:'<svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2a10 10 0 100 20 10 10 0 000-20m0 4a6 6 0 100 12 6 6 0 000-12m0 4a2 2 0 100 4 2 2 0 000-4"/></svg>',doc:'<svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M6 2h9l5 5v15H6zm8 1.5V8h4.5"/></svg>'};
function velOf(c){const kw=+c.kw||0;if(c.t==='DC'||kw>=50)return'DC';if(kw<=7)return'AC_lenta';return'AC_semi';}
const COLS={BEV:'#2563EB',PHEV:'#16A34A',HEV:'#F59E0B',MHEV:'#7C3AED',EBUS:'#0D9488',ETRUCK:'#EF4444'};
const REGS=()=>DB.regiones_orden;
const fopt=(arr,sel)=>arr.map(r=>`<option value="${r}"${sel===r?' selected':''}>${r}</option>`).join('');
function ind(lbl,val,unit){return `<div style="background:#fff;border:1px solid var(--line);border-radius:12px;padding:13px 15px"><div style="font-size:12px;color:var(--muted);font-weight:600">${lbl}</div><div style="font-size:22px;font-weight:800;margin-top:3px">${val}${unit?`<small style="font-size:13px;color:var(--muted);font-weight:700"> ${unit}</small>`:''}</div></div>`;}
function rankRows(arr,fmtv){const mx=arr.length?arr[0][1]:1;return arr.map((o,i)=>`<div class="rank" style="padding:7px 0;border-bottom:1px solid var(--line)"><div class="legrow"><span style="width:20px;font-weight:800;color:var(--muted)">${i+1}</span><span class="nm" style="text-transform:capitalize">${o[0]}</span><span class="vl">${fmtv?fmtv(o[1]):fint(o[1])}</span></div><div class="bar"><i style="width:${(o[1]/mx*100).toFixed(0)}%"></i></div></div>`).join('');}
/* tabs */
function tabsNav(sec,tabs){return `<div class="tabs">${tabs.map(t=>`<button data-tab="${sec}:${t.id}" class="${TAB[sec]===t.id?'active':''}">${t.label}</button>`).join('')}</div><div id="tabpanel"></div>`;}
function showTab(sec,id){TAB[sec]=id;$$(`.tabs button`).forEach(b=>b.classList.toggle('active',b.dataset.tab===sec+':'+id));renderTab(sec);}

/* ===== INICIO ===== */
function pageInicio(){const r=DB.resumen;const K=DB.kpis_inicio||[];
  const cards=K.map(k=>`<div class="kbar" style="border-left-color:${k.c}"><div class="kbar-top"><span class="kbar-lbl">${k.t}</span><span class="kbar-i" title="${k.info}">i</span></div><div class="kbar-val" style="color:${k.c}">${k.v}</div><div class="kbar-sub">${k.sub}</div><div class="kbar-delta">▲ ${k.delta}</div></div>`).join('');
  return `<div class="hero"><h1>El observatorio de electromovilidad y energía de Chile</h1><p>Datos oficiales de vehículos eléctricos, infraestructura de carga, generación renovable y almacenamiento — actualizados y listos para decidir dónde invertir.</p><div class="herobtns"><button class="btn btn-primary" data-go="resumen">Ver resumen ejecutivo</button><button class="btn btn-ghost" data-go="infra">Explorar infraestructura</button></div></div>
   <h2 style="font-size:17px;font-weight:800;margin:24px 0 12px">Indicadores clave</h2>
   <div class="kbar-grid">${cards}</div>`;};
function renderTab(sec){killViz();const fn=TABFN[sec]&&TABFN[sec][TAB[sec]];const panel=$('#tabpanel');if(panel&&fn)panel.innerHTML=fn();}
async function go(id){killViz();const main=$('#main');main.innerHTML='<div style="padding:60px;text-align:center;color:var(--muted)">Cargando…</div>';$$('.nav-links a').forEach(a=>a.classList.toggle('active',a.dataset.go===id));document.getElementById('navlinks').classList.remove('open');window.scrollTo(0,0);
  let html;try{html=await PAGES[id]();}catch(e){main.innerHTML='<p style="padding:40px">Error: '+e+'</p>';return;}
  main.innerHTML=`<section class="page active">${html}</section>`;
  if(BIND[id])BIND[id]();
  const SEC={mercado:'merc',energia:'ener',inversion:'inv',reportes:'rep'};
  const sk=SEC[id]||id;
  if(TABFN[sk])renderTab(sk);}
document.addEventListener('click',e=>{const tb=e.target.closest('[data-tab]');if(tb){const[s,i]=tb.dataset.tab.split(':');showTab(s,i);return;}const row=e.target.closest('tr[data-com]');if(row){F.calc.comuna=row.dataset.com;const sel=$('#cf-com');if(sel)sel.value=row.dataset.com;TAB.calc='detalle';$$('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab==='calc:detalle'));renderTab('calc');return;}const g=e.target.closest('[data-go]');if(g){e.preventDefault();go(g.dataset.go);}});
Promise.all([fetch('data/datos.json?v='+V).then(r=>r.json()),fetch('data/cargadores.json?v='+V).then(r=>r.json())]).then(([d,c])=>{DB=d;CARG=c;const ff=$('#foot-fecha');if(ff)ff.textContent='Actualizado '+d.fecha;go('inicio');}).catch(e=>{$('#main').innerHTML='<p style="padding:40px">Error cargando datos: '+e+'</p>';});

/* ===== INFRA: pestañas extra ===== */
function tabInfraEvol(){const X=DATA.infra_extra.evol;
  setTimeout(()=>{const cx=$('#if-evol');if(cx)chart(cx,{type:'line',data:{labels:X.labels,datasets:[{label:'Vehículos eléctricos',data:X.evs,borderColor:'#16A34A',backgroundColor:'rgba(22,163,74,.1)',fill:true,tension:.3,yAxisID:'y'},{label:'Conectores públicos',data:X.conect,borderColor:'#2563EB',backgroundColor:'rgba(37,99,235,.1)',fill:true,tension:.3,yAxisID:'y1'}]},options:{maintainAspectRatio:false,plugins:{legend:{position:'bottom',labels:{boxWidth:12,font:{size:11}}}},scales:{y:{position:'left',title:{display:true,text:'EVs'}},y1:{position:'right',grid:{drawOnChartArea:false},title:{display:true,text:'Conectores'}}}}});},60);
  return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Evolución de la red y la flota</h3><div class="subtitle">Vehículos eléctricos y conectores públicos por año (${X.labels[0]}–${X.labels.at(-1)}).</div><div style="position:relative;height:320px"><canvas id="if-evol"></canvas></div><div class="card-src">Fuente: SEC · ANAC · ${DB.fecha}</div></div>`;}
function tabInfraDist(){const X=DATA.infra_extra;
  setTimeout(()=>{const a=$('#if-conect');if(a)chart(a,{type:'doughnut',data:{labels:X.conectTipo.labels,datasets:[{data:X.conectTipo.vals,backgroundColor:['#2563EB','#16A34A','#F59E0B','#7C3AED','#EF4444','#0D9488','#64748B'],borderWidth:0}]},options:{cutout:'58%',plugins:{legend:{position:'right',labels:{boxWidth:11,font:{size:10}}}},maintainAspectRatio:false}});
    const b=$('#if-acdc');if(b)chart(b,{type:'bar',data:{labels:X.acdc.labels,datasets:[{label:'AC',data:X.acdc.ac,backgroundColor:'#2563EB'},{label:'DC',data:X.acdc.dc,backgroundColor:'#EF4444'}]},options:{maintainAspectRatio:false,plugins:{legend:{position:'bottom'}},scales:{x:{stacked:true,ticks:{font:{size:9}}},y:{stacked:true}}}});
    const c=$('#if-top');if(c)chart(c,{type:'bar',data:{labels:X.top.labels,datasets:[{data:X.top.vals,backgroundColor:'#2563EB'}]},options:{indexAxis:'y',maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{ticks:{font:{size:9}}}}}});},60);
  return `<div class="card" style="margin-bottom:16px"><span class="datechip">📅 ${DB.fecha}</span><h3>Conectores por tipo y por región</h3><div class="subtitle">Tipo de conector y distribución AC/DC por región.</div><div class="grid g2"><div style="position:relative;height:260px"><canvas id="if-conect"></canvas></div><div style="position:relative;height:260px"><canvas id="if-acdc"></canvas></div></div><div class="card-src">Fuente: SEC · ${DB.fecha}</div></div>
   <div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Top 20 comunas por conectores</h3><div class="subtitle">Comunas con mayor número de conectores públicos.</div><div style="position:relative;height:460px"><canvas id="if-top"></canvas></div><div class="card-src">Fuente: SEC · ${DB.fecha}</div></div>`;}

/* ===== MERCADO: pestaña Por región ===== */
function tabMercRegion(){const RY=DATA.mercado_extra.regYearly;const yrs=Object.keys(RY).sort();const last=RY[yrs.at(-1)];
  setTimeout(()=>{const cx=$('#mc-reg');if(cx)chart(cx,{type:'bar',data:{labels:last.labels,datasets:[{data:last.data||last.evs||last.vals,backgroundColor:'#16A34A'}]},options:{indexAxis:'y',maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{ticks:{font:{size:10}}}}}});
    const px=$('#mc-pen');if(px){const ps=DB.resumen.penetracion.serie;chart(px,{type:'line',data:{labels:ps.map((_,i)=>i+1),datasets:[{label:'Penetración %',data:ps,borderColor:'#2563EB',backgroundColor:'rgba(37,99,235,.1)',fill:true,tension:.3}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{display:false}}}});}},60);
  const dataArr=last.data||last.evs||last.vals||[];
  return `<div class="card" style="margin-bottom:16px"><span class="datechip">📅 ${DB.fecha}</span><h3>Vehículos eléctricos por región (${yrs.at(-1)})</h3><div class="subtitle">Flota acumulada por región.</div><div style="position:relative;height:420px"><canvas id="mc-reg"></canvas></div><div class="card-src">Fuente: ANAC · permisos de circulación · ${DB.fecha}</div></div>
   <div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Penetración EV mensual</h3><div class="subtitle">Participación de electrificados en ventas (últimos meses).</div><div style="position:relative;height:240px"><canvas id="mc-pen"></canvas></div><div class="card-src">Fuente: ANAC · ${DB.fecha}</div></div>`;}

/* ===== ENERGIA: pestañas BESS y Solar ===== */
function tabEnerBess(){const X=DATA.energia_extra;
  setTimeout(()=>{const a=$('#en-bess-anio');if(a&&X.bessAnio)chart(a,{type:'bar',data:{labels:X.bessAnio.labels,datasets:[{label:'MW',data:X.bessAnio.mw,backgroundColor:'#7C3AED'}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{ticks:{font:{size:10}}}}}});
    const b=$('#en-bess-estado');if(b)chart(b,{type:'doughnut',data:{labels:X.bessEstado.labels,datasets:[{data:X.bessEstado.mwh,backgroundColor:['#94A3B8','#F59E0B','#0EA5E9','#16A34A','#7C3AED'],borderWidth:0}]},options:{cutout:'58%',plugins:{legend:{position:'right',labels:{boxWidth:11,font:{size:10}}}},maintainAspectRatio:false}});
    const c=$('#en-bess-tech');if(c)chart(c,{type:'bar',data:{labels:X.bessTech.labels,datasets:[{data:X.bessTech.mw,backgroundColor:'#0D9488'}]},options:{indexAxis:'y',maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{ticks:{font:{size:9}}}}}});},60);
  return `<div class="card" style="margin-bottom:16px"><span class="datechip">📅 ${DB.fecha}</span><h3>Almacenamiento BESS</h3><div class="subtitle">${fint(X.bessTot.mwhAlmacenamiento)} MWh en cartera · ${fint(X.bessTot.proyectos)} proyectos. Capacidad por año de entrada y por estado.</div><div class="grid g2"><div style="position:relative;height:260px"><canvas id="en-bess-anio"></canvas></div><div style="position:relative;height:260px"><canvas id="en-bess-estado"></canvas></div></div><div class="card-src">Fuente: CEN · SEIA · ${DB.fecha}</div></div>
   <div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Capacidad total por tecnología (cartera)</h3><div class="subtitle">MW por fuente en toda la cartera (operativos + en desarrollo).</div><div style="position:relative;height:300px"><canvas id="en-bess-tech"></canvas></div><div class="card-src">Fuente: CEN · ${DB.fecha}</div></div>`;}
function tabEnerSolar(){const S=DATA.energia_extra.solar;
  setTimeout(()=>{const a=$('#en-sol-ins');if(a)chart(a,{type:'line',data:{labels:S.solarInscrita.labels,datasets:[{label:'GW inscritos',data:S.solarInscrita.solar,borderColor:'#F59E0B',backgroundColor:'rgba(245,158,11,.12)',fill:true,tension:.3}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false}}}});
    const b=$('#en-sol-anual');if(b)chart(b,{type:'bar',data:{labels:S.instalAnual.labels,datasets:[{label:'MW/año',data:S.instalAnual.solar,backgroundColor:'#F59E0B'}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{ticks:{font:{size:9}}}}}});
    const c=$('#en-sol-reg');if(c)chart(c,{type:'bar',data:{labels:S.solarRegion.labels,datasets:[{data:S.solarRegion.mw,backgroundColor:'#CA8A04'}]},options:{indexAxis:'y',maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{ticks:{font:{size:10}}}}}});},60);
  return `<div class="card" style="margin-bottom:16px"><span class="datechip">📅 ${DB.fecha}</span><h3>Energía solar — capacidad y crecimiento</h3><div class="subtitle">${fint(S.totales.mwOperativo)} MW operativos · ${fint(S.totales.proyectos)} proyectos. Top región: ${S.totales.topRegion}.</div><div class="grid g2"><div style="position:relative;height:250px"><canvas id="en-sol-ins"></canvas></div><div style="position:relative;height:250px"><canvas id="en-sol-anual"></canvas></div></div><div class="card-src">Fuente: CEN · ${DB.fecha}</div></div>
   <div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Potencia solar por región</h3><div class="subtitle">MW solares operativos por región.</div><div style="position:relative;height:320px"><canvas id="en-sol-reg"></canvas></div><div class="card-src">Fuente: CEN · ${DB.fecha}</div></div>`;}

/* ===== CENSO & ELECTROMOVILIDAD ===== */
async function pageCenso(){await Promise.all([load('censo'),load('coords').then(d=>COORDS=d)]);F.censo=F.censo||{};TAB.censo=TAB.censo||'viviendas';
  return `<div class="page-head"><h1>Censo & Electromovilidad</h1><p class="sub">Población, viviendas, licencias de conducir y potencial de carga domiciliaria por región (INE Censo 2024).</p></div>
   ${tabsNav('censo',[{id:'viviendas',label:'Viviendas'},{id:'personas',label:'Personas y licencias'},{id:'mapa',label:'Mapa por región'}])}`;}
function tabCensoViv(){const R=DATA.censo.reg;const tot=R.reduce((a,x)=>a+x.tot,0);
  setTimeout(()=>{const a=$('#cn-viv');if(a)chart(a,{type:'bar',data:{labels:R.map(x=>x.r),datasets:[{label:'Viviendas (miles)',data:R.map(x=>Math.round(x.tot/1000)),backgroundColor:'#2563EB'}]},options:{indexAxis:'y',maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{ticks:{font:{size:9}}}}}});
    const b=$('#cn-inst');if(b)chart(b,{type:'bar',data:{labels:R.map(x=>x.r),datasets:[{label:'% con instalación eléctrica adecuada',data:R.map(x=>x.inst),backgroundColor:'#16A34A'}]},options:{indexAxis:'y',maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{ticks:{font:{size:9}}},x:{max:100}}}});},60);
  return `<div class="grid g4" style="margin-bottom:16px">${ind('Viviendas totales',fint(tot))}${ind('Regiones',R.length)}${ind('% urbano (prom.)',fmt(R.reduce((a,x)=>a+x.urb,0)/R.length),'%')}${ind('% departamentos (prom.)',fmt(R.reduce((a,x)=>a+x.dpto,0)/R.length),'%')}</div>
   <div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Viviendas y potencial de carga domiciliaria</h3><div class="subtitle">Total de viviendas y porcentaje con instalación eléctrica adecuada por región.</div><div class="grid g2"><div style="position:relative;height:430px"><canvas id="cn-viv"></canvas></div><div style="position:relative;height:430px"><canvas id="cn-inst"></canvas></div></div><div class="card-src">Fuente: INE Censo 2024 · ${DB.fecha}</div></div>`;}
function tabCensoPers(){const P=DATA.censo.pers,LA=DATA.censo.licAge;const pop=P.reduce((a,x)=>a+x.pop,0);const cond=P.reduce((a,x)=>a+x.cond,0);
  setTimeout(()=>{const a=$('#cn-pop');if(a)chart(a,{type:'bar',data:{labels:P.map(x=>x.r),datasets:[{label:'Población (miles)',data:P.map(x=>Math.round(x.pop/1000)),backgroundColor:'#7C3AED'}]},options:{indexAxis:'y',maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{ticks:{font:{size:9}}}}}});
    const b=$('#cn-lic');if(b){const ks=Object.keys(LA);const lbl={a0:'<15',a15:'15-17',a18:'18-29',a30:'30-44',a45:'45-59',a60:'60+'};chart(b,{type:'bar',data:{labels:ks.map(k=>lbl[k]||k),datasets:[{label:'Tasa de licencia',data:ks.map(k=>LA[k]),backgroundColor:'#0EA5E9'}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{max:1}}}});}},60);
  return `<div class="grid g4" style="margin-bottom:16px">${ind('Población total',fint(pop))}${ind('Conductores',fint(cond))}${ind('% con licencia (prom.)',fmt(P.reduce((a,x)=>a+x.lic,0)/P.length),'%')}${ind('Regiones',P.length)}</div>
   <div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Población y licencias de conducir</h3><div class="subtitle">Población por región y tasa de licencia por grupo de edad.</div><div class="grid g2"><div style="position:relative;height:430px"><canvas id="cn-pop"></canvas></div><div style="position:relative;height:430px"><canvas id="cn-lic"></canvas></div></div><div class="card-src">Fuente: INE Censo 2024 · ${DB.fecha}</div></div>`;}
function tabCensoMapa(){F.censo.metric=F.censo.metric||'tot';const R=DATA.censo.reg;
  const metrics={tot:['Viviendas','#2563EB',x=>x.tot],inst:['% instalación eléctrica','#16A34A',x=>x.inst],urb:['% urbano','#F59E0B',x=>x.urb]};
  setTimeout(()=>{const sel=$('#cn-metric');if(sel)sel.onchange=e=>{F.censo.metric=e.target.value;renderTab('censo');};
    const m=leaflet('cn-map',[-35.5,-71.3]);const mf=metrics[F.censo.metric];const vals=R.map(mf[2]);const mx=Math.max(...vals);
    R.forEach(x=>{const co=COORDS.region[x.r];if(!co)return;const v=mf[2](x);L.circleMarker(co,{radius:8+v/mx*22,color:mf[1],fillColor:mf[1],fillOpacity:.5,weight:1.5}).bindPopup(`<b>${x.r}</b><br>Viviendas: ${fint(x.tot)}<br>% instal.: ${x.inst}<br>% urbano: ${x.urb}<br>% deptos: ${x.dpto}`).addTo(m);});},60);
  return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Mapa por región</h3><div class="subtitle">Tamaño de la burbuja según el indicador seleccionado.</div>
   <div class="filterbar" style="box-shadow:none;border:none;padding:6px 0;margin:4px 0"><div class="fgroup"><label>Indicador</label><select id="cn-metric"><option value="tot"${F.censo.metric==='tot'?' selected':''}>Viviendas totales</option><option value="inst"${F.censo.metric==='inst'?' selected':''}>% instalación eléctrica</option><option value="urb"${F.censo.metric==='urb'?' selected':''}>% urbano</option></select></div></div>
   <div id="cn-map" style="height:480px;border-radius:12px;border:1px solid var(--line)"></div><div class="card-src">Fuente: INE Censo 2024 · ${DB.fecha}</div></div>`;}
