/* ===== Observatorio EV · v3 (tabs + filtros + mapas) ===== */
let DB=null,CARG=null,COORDS=null,REP=null;
const DATA={}, F={}, TAB={};
let _charts=[], _maps=[];
const fmt=n=>(Math.round((n||0)*10)/10).toLocaleString('es-CL');
const fint=n=>Math.round(n||0).toLocaleString('es-CL');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const norm=s=>(s||'').toString().toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'').trim();
const V='1781998079';
async function load(n){if(DATA[n])return DATA[n];DATA[n]=await fetch(`data/${n}.json?v=${V}`).then(r=>r.json());return DATA[n];}
function killViz(){_charts.forEach(c=>{try{c.destroy()}catch(e){}});_charts=[];_maps.forEach(m=>{try{m.remove()}catch(e){}});_maps=[];}
function chart(ctx,cfg){const c=new Chart(ctx,cfg);_charts.push(c);return c;}
function leaflet(id,view){const m=L.map(id,{scrollWheelZoom:false}).setView(view||[-35.5,-71.3],5);
  L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{maxZoom:18,attribution:'© OpenStreetMap, © CARTO'}).addTo(m);_maps.push(m);return m;}
const datechip=()=>`<span class="datechip">📅 ${DB.fecha}</span>`;
function spark(serie,color){if(!serie||serie.length<2)return'';const w=120,h=34,mn=Math.min(...serie),mx=Math.max(...serie),rg=(mx-mn)||1;
  const pts=serie.map((v,i)=>[i/(serie.length-1)*w,h-((v-mn)/rg)*(h-6)-3]);
  const dd=pts.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+' '+p[1].toFixed(1)).join(' ');const id='g'+Math.random().toString(36).slice(2,7);
  return `<svg class="spark" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><defs><linearGradient id="${id}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${color}" stop-opacity=".25"/><stop offset="1" stop-color="${color}" stop-opacity="0"/></linearGradient></defs><path d="${dd} L${w} ${h} L0 ${h} Z" fill="url(#${id})"/><path d="${dd}" fill="none" stroke="${color}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><circle cx="${pts.at(-1)[0].toFixed(1)}" cy="${pts.at(-1)[1].toFixed(1)}" r="3" fill="${color}"/></svg>`;}
function kpi(o){return `<div class="kpi"><div class="top"><div class="ico" style="background:${o.bg};color:${o.c}">${o.icon}</div><div class="lbl">${o.lbl}</div></div><div class="val">${o.val}${o.unit?`<small>${o.unit}</small>`:''}</div>${o.serie?spark(o.serie,o.c):''}</div>`;}
const IC={bolt:'<svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M13 2L3 14h7l-1 8 10-12h-7z"/></svg>',car:'<svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M5 11l1.5-4.5h11L19 11m-1.5 5a1.5 1.5 0 110-3 1.5 1.5 0 010 3m-11 0a1.5 1.5 0 110-3 1.5 1.5 0 010 3M19 6.5A1.5 1.5 0 0017.5 5h-11A1.5 1.5 0 005 6.5L3 12v8h2v-2h14v2h2v-8z"/></svg>',plug:'<svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M7 2v6m10-6v6M5 8h14v2a7 7 0 01-6 6.9V22h-2v-5.1A7 7 0 015 10z"/></svg>',map:'<svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2a7 7 0 00-7 7c0 5 7 13 7 13s7-8 7-13a7 7 0 00-7-7m0 9.5A2.5 2.5 0 1112 6a2.5 2.5 0 010 5.5"/></svg>',sun:'<svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M12 7a5 5 0 100 10 5 5 0 000-10m0-5v3m0 14v3M2 12h3m14 0h3M4.2 4.2l2.1 2.1m11.4 11.4l2.1 2.1M4.2 19.8l2.1-2.1M17.7 6.3l2.1-2.1"/></svg>',bat:'<svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M4 8h14v8H4zm15 2h2v4h-2M7 10l3 0-1 2 2 0-3 4 1-3-2 0z"/></svg>',target:'<svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2a10 10 0 100 20 10 10 0 000-20m0 4a6 6 0 100 12 6 6 0 000-12m0 4a2 2 0 100 4 2 2 0 000-4"/></svg>',doc:'<svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M6 2h9l5 5v15H6zm8 1.5V8h4.5"/></svg>'};
function velOf(c){const kw=+c.kw||0;if(c.t==='DC'||kw>=50)return'DC';if(kw<=7)return'AC_lenta';return'AC_semi';}
const COLS={BEV:'#2563EB',PHEV:'#16A34A',HEV:'#F59E0B',MHEV:'#7C3AED',EBUS:'#0D9488',ETRUCK:'#EF4444'};
const REGS=()=>DB.regiones_orden;
const fopt=(arr,sel)=>arr.map(r=>`<option value="${r}"${sel===r?' selected':''}>${r}</option>`).join('');
function ind(lbl,val,unit){return `<div style="background:#fff;border:1px solid var(--line);border-radius:12px;padding:13px 15px"><div style="font-size:12px;color:var(--muted);font-weight:600">${lbl}</div><div style="font-size:22px;font-weight:800;margin-top:3px">${val}${unit?`<small style="font-size:13px;color:var(--muted);font-weight:700"> ${unit}</small>`:''}</div></div>`;}
function rankRows(arr,fmtv){const mx=arr.length?arr[0][1]:1;return arr.map((o,i)=>`<div class="rank" style="padding:7px 0;border-bottom:1px solid var(--line)"><div class="legrow"><span style="width:20px;font-weight:800;color:var(--muted)">${i+1}</span><span class="nm" style="text-transform:capitalize">${o[0]}</span><span class="vl">${fmtv?fmtv(o[1]):fint(o[1])}</span></div><div class="bar"><i style="width:${(o[1]/mx*100).toFixed(0)}%"></i></div></div>`).join('');}
/* tabs */
function tabsNav(sec,tabs){return `<div class="tabs">${tabs.map(t=>`<button data-tab="${sec}:${t.id}" class="${TAB[sec]===t.id?'active':''}">${t.label}</button>`).join('')}</div><div id="tabpanel"></div>`;}
function showTab(sec,id){TAB[sec]=id;$$(`.tabs button`).forEach(b=>b.classList.toggle('active',b.dataset.tab===sec+':'+id));renderTab(sec);}

/* ===== INICIO ===== */
function pageInicio(){const r=DB.resumen;const K=DB.kpis_inicio||[];const card=k=>`<div class="kbar" style="border-left-color:${k.c}"><div class="kbar-top"><span class="kbar-lbl">${k.t}</span><button class="kbar-i" data-info="${(k.info||'').replace(/"/g,'&quot;')}" aria-label="Más información">i</button></div><div class="kbar-val" style="color:${k.c}">${k.v}</div><div class="kbar-sub">${k.sub}</div>${k.delta?`<div class="kbar-delta">▲ ${k.delta}</div>`:''}</div>`;
  const grupos=[...new Set(K.map(k=>k.g||'Indicadores'))];
  const bloques=grupos.map(g=>`<h3 class="kgroup">${g}</h3><div class="kbar-grid">${K.filter(k=>(k.g||'Indicadores')===g).map(card).join('')}</div>`).join('');return `<div class="hero"><h1>El observatorio de electromovilidad y energía de Chile</h1><p>Datos oficiales de vehículos eléctricos, infraestructura de carga, generación renovable y almacenamiento — actualizados y listos para decidir dónde invertir.</p><div class="herobtns"><button class="btn btn-primary" data-go="resumen">Ver resumen ejecutivo</button><button class="btn btn-ghost" data-go="infra">Explorar infraestructura</button></div></div>
  <h2 style="font-size:18px;font-weight:800;margin:24px 0 6px">Indicadores clave</h2>
   ${bloques}`;}

/* ===== RESUMEN (filtro región + tabs) ===== */
function regKey(r){const ks=Object.keys(REP.reg);const nk=x=>norm(x).replace(/\./g,'');return ks.find(k=>nk(k)===nk(r))||ks.find(k=>nk(r).includes(nk(k))||nk(k).includes(nk(r)));}
async function pageResumen(){await Promise.all([load('reportes').then(d=>REP=d),load('coords').then(d=>COORDS=d)]);
  F.resumen=F.resumen||{region:''};TAB.resumen=TAB.resumen||'ind';
  return `<div class="page-head"><h1>Resumen Ejecutivo</h1><p class="sub">Indicadores clave del ecosistema de electromovilidad y energía en Chile.</p><div class="meta"><span class="pill">📅 Actualizado: ${DB.fecha}</span></div></div>
   <div class="filterbar"><div class="fgroup"><label>Región</label><select id="rs-reg"><option value="">Todo Chile</option>${fopt(REGS(),F.resumen.region)}</select></div><button class="btn btn-ghost" id="rs-reset" style="align-self:flex-end">Limpiar</button></div>
   ${tabsNav('resumen',[{id:'ind',label:'Indicadores'},{id:'mapa',label:'Mapa de la red'}])}`;}
function bindResumen(){$('#rs-reg').onchange=e=>{F.resumen.region=e.target.value;renderTab('resumen');};$('#rs-reset').onclick=()=>{F.resumen.region='';$('#rs-reg').value='';renderTab('resumen');};}
function tabResumenInd(){const r=DB.resumen,f=F.resumen;let cards;
  if(!f.region){cards=[kpi({lbl:'Penetración EV (mensual)',val:(''+r.penetracion.valor).replace('.',','),unit:'%',serie:r.penetracion.serie,bg:'#EFF6FF',c:'#2563EB',icon:IC.bolt}),kpi({lbl:'Flota EV enchufable acumulada',val:fint(r.evs_acum.valor),serie:r.evs_acum.serie,bg:'#ECFDF5',c:'#16A34A',icon:IC.car}),kpi({lbl:'Conectores públicos',val:fint(r.conectores.valor),bg:'#FEF3C7',c:'#F59E0B',icon:IC.plug}),kpi({lbl:'Comunas sin cargador',val:fint(r.comunas_sin.valor),unit:'/ '+r.comunas_sin.de,bg:'#FEE2E2',c:'#EF4444',icon:IC.map}),kpi({lbl:'Potencia renovable operativa',val:fint(r.ernc_mw.valor),unit:'MW',bg:'#FEF9C3',c:'#CA8A04',icon:IC.sun}),kpi({lbl:'Almacenamiento BESS',val:fint(r.bess_mwh.valor),unit:'MWh',bg:'#F3E8FF',c:'#7C3AED',icon:IC.bat})].join('');
  }else{const rg=REP.reg[regKey(f.region)]||{};cards=[kpi({lbl:'Vehículos eléctricos',val:fint(rg.evs),bg:'#ECFDF5',c:'#16A34A',icon:IC.car}),kpi({lbl:'Conectores públicos',val:fint(rg.con),bg:'#FEF3C7',c:'#F59E0B',icon:IC.plug}),kpi({lbl:'Cargadores DC',val:fint(rg.dc),bg:'#EFF6FF',c:'#2563EB',icon:IC.bolt}),kpi({lbl:'Comunas sin cargador',val:fint(rg.sincarg),unit:'/ '+rg.comunas,bg:'#FEE2E2',c:'#EF4444',icon:IC.map}),kpi({lbl:'Potencia renovable operativa',val:fint(rg.ernc_mw),unit:'MW',bg:'#FEF9C3',c:'#CA8A04',icon:IC.sun}),kpi({lbl:'EV por 1.000 hab.',val:(''+rg.evs_1000).replace('.',','),bg:'#F3E8FF',c:'#7C3AED',icon:IC.target})].join('');}
  const amb=f.region||'Chile';
  return `<div class="grid g3">${cards}</div><div class="insight"><div class="ic">i</div><div><b>Lectura ejecutiva (${amb}).</b> ${f.region?`La región tiene ${fint((REP.reg[regKey(f.region)]||{}).evs)} vehículos eléctricos y ${fint((REP.reg[regKey(f.region)]||{}).con)} conectores públicos, con ${fint((REP.reg[regKey(f.region)]||{}).sincarg)} comunas aún sin carga.`:`Penetración EV mensual de ${(''+r.penetracion.valor).replace('.',',')}%, flota de ${fint(r.evs_acum.valor)} enchufables y ${fint(r.conectores.valor)} conectores; ${fint(r.comunas_sin.valor)} de ${r.comunas_sin.de} comunas sin carga.`}</div></div><div class="srcleg"><b>Fuente de cada indicador (pestaña de origen):</b><ul><li><b>Penetración EV</b> y <b>Flota EV enchufable</b> → sección <a data-go="mercado">Mercado EV</a></li><li><b>Conectores públicos</b> y <b>Comunas sin cargador</b> → sección <a data-go="infra">Infraestructura</a></li><li><b>Potencia renovable operativa</b> y <b>Almacenamiento BESS</b> → sección <a data-go="energia">Energía y BESS</a></li></ul><span class="srcdate">📅 Datos actualizados al ${DB.fecha}. Fuentes: SEC · ANAC · CEN · INE Censo 2024.</span></div>`;}
function tabResumenMapa(){const f=F.resumen;
  setTimeout(()=>{const D=CARG.filter(c=>!f.region||c.r===f.region);const m=leaflet('rs-map',f.region?undefined:[-35.5,-71.3]);const col=c=>({AC_lenta:'#16A34A',AC_semi:'#2563EB',DC:'#EF4444'})[velOf(c)];const pts=[];D.forEach(c=>{if(!c.lat||!c.lng)return;pts.push([c.lat,c.lng]);L.circleMarker([c.lat,c.lng],{radius:3,color:col(c),fillColor:col(c),fillOpacity:.7,weight:0}).addTo(m);});if(f.region&&pts.length){try{m.fitBounds(pts,{padding:[25,25],maxZoom:10})}catch(e){}}},60);
  return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Red nacional de carga pública</h3><div class="subtitle">${fint(CARG.filter(c=>!f.region||c.r===f.region).length)} conectores en ${f.region||'todo Chile'}.</div><div id="rs-map" style="height:480px;border-radius:12px;border:1px solid var(--line)"></div><div style="display:flex;gap:18px;margin-top:10px;font-size:12.5px;flex-wrap:wrap"><span class="legrow"><i class="dot" style="background:#16A34A"></i> AC lenta</span><span class="legrow"><i class="dot" style="background:#2563EB"></i> AC semi</span><span class="legrow"><i class="dot" style="background:#EF4444"></i> DC rápida</span></div><div class="card-src">Fuente: SEC · ${DB.fecha}</div></div>`;}

/* ===== INFRAESTRUCTURA (tabs) ===== */
async function pageInfra(){await load('infra_extra');await load('precios_acdc');F.infra=F.infra||{region:'',vel:'',comuna:'',con:''};TAB.infra=TAB.infra||'mapa';
  const comunas=F.infra.region?[...new Set(CARG.filter(c=>c.r===F.infra.region&&c.c).map(c=>c.c))].sort((a,b)=>a.localeCompare(b)):[];
  const conTipos=[...new Set(CARG.map(c=>c.cn).filter(Boolean))].sort();
  return `<div class="page-head"><h1>Infraestructura de Carga</h1><p class="sub">Distribución, tecnología y operadores de la red pública de carga.</p></div>
   <div class="filterbar"><div class="fgroup"><label>Región</label><select id="if-reg"><option value="">Todo Chile</option>${fopt(REGS(),F.infra.region)}</select></div><div class="fgroup"><label>Comuna</label><select id="if-com"><option value="">Todas</option>${comunas.map(c=>`<option value="${c}"${F.infra.comuna===c?' selected':''}>${c}</option>`).join('')}</select></div><div class="fgroup"><label>Tipo de carga</label><select id="if-vel"><option value="">Todas</option><option value="AC"${F.infra.vel==='AC'?' selected':''}>AC</option><option value="DC"${F.infra.vel==='DC'?' selected':''}>DC</option></select></div><div class="fgroup"><label>Tipo de conector</label><select id="if-con"><option value="">Todos</option>${conTipos.map(c=>`<option value="${c}"${F.infra.con===c?' selected':''}>${c}</option>`).join('')}</select></div><button class="btn btn-ghost" id="if-reset" style="align-self:flex-end">Limpiar filtros</button></div>
   <div class="grid g4" id="if-kpis" style="margin-bottom:16px"></div>
   <div id="if-precios" style="margin-bottom:18px"></div>
   ${tabsNav('infra',[{id:'mapa',label:'Mapa'},{id:'tech',label:'Tecnología'},{id:'oper',label:'Operadores'},{id:'evol',label:'Evolución'},{id:'dist',label:'Distribución'},{id:'precios',label:'Precios AC/DC'}])}`;}
function tipoAD(c){return (c.t==='DC'||(+c.kw||0)>=50)?'DC':'AC';}
function conesDisp(){const f=F.infra;return [...new Set(CARG.filter(c=>(!f.region||c.r===f.region)&&(!f.comuna||c.c===f.comuna)&&(!f.vel||tipoAD(c)===f.vel)&&c.cn).map(c=>c.cn))].sort();}
function fillConSelect(){const opts=conesDisp();if(F.infra.con&&!opts.includes(F.infra.con))F.infra.con='';const sel=$('#if-con');if(sel)sel.innerHTML='<option value="">Todos</option>'+opts.map(c=>`<option value="${c}"${F.infra.con===c?' selected':''}>${c}</option>`).join('');}
function infraData(){const f=F.infra;return CARG.filter(c=>(!f.region||c.r===f.region)&&(!f.comuna||c.c===f.comuna)&&(!f.vel||tipoAD(c)===f.vel)&&(!f.con||c.cn===f.con));}
function bindInfra(){const re=()=>{infraKpis();renderTab('infra');};
  $('#if-reg').onchange=e=>{F.infra.region=e.target.value;F.infra.comuna='';const cs=[...new Set(CARG.filter(c=>c.r===F.infra.region&&c.c).map(c=>c.c))].sort((a,b)=>a.localeCompare(b));$('#if-com').innerHTML='<option value="">Todas</option>'+cs.map(c=>`<option value="${c}">${c}</option>`).join('');fillConSelect();re();};
  $('#if-com').onchange=e=>{F.infra.comuna=e.target.value;fillConSelect();re();};
  $('#if-vel').onchange=e=>{F.infra.vel=e.target.value;fillConSelect();re();};
  $('#if-con').onchange=e=>{F.infra.con=e.target.value;re();};
  $('#if-reset').onclick=()=>{F.infra={region:'',vel:'',comuna:'',con:''};$('#if-reg').value='';$('#if-com').innerHTML='<option value="">Todas</option>';$('#if-vel').value='';fillConSelect();re();};}
function infraKpis(){const D=infraData(),f=F.infra;const comunas=new Set(D.filter(c=>c.c).map(c=>norm(c.c)));const totCom=f.region?(DB.comunas_por_region[f.region]||0):346;const sin=Math.max(totCom-comunas.size,0);const pot=D.reduce((a,c)=>a+(+c.kw||0),0)/1000;
  const el=$('#if-kpis');if(el)el.innerHTML=[kpi({lbl:'Conectores públicos',val:fint(D.length),bg:'#FEF3C7',c:'#F59E0B',icon:IC.plug}),kpi({lbl:'Comunas con carga',val:fint(comunas.size),bg:'#ECFDF5',c:'#16A34A',icon:IC.map}),kpi({lbl:'Comunas sin carga',val:fint(sin),unit:'/ '+totCom,bg:'#FEE2E2',c:'#EF4444',icon:IC.map}),kpi({lbl:'Potencia instalada',val:fmt(pot),unit:'MW',bg:'#EFF6FF',c:'#2563EB',icon:IC.bolt})].join('');
  // precios de carga (kWh) min / promedio / max de la selección
  const pr=D.map(c=>c.p).filter(v=>v>0);const pe=$('#if-precios');
  if(pe){if(pr.length){const mn=Math.min(...pr),mx=Math.max(...pr),av=pr.reduce((a,b)=>a+b,0)/pr.length;const amb=f.comuna||f.region||'todo Chile';
    pe.innerHTML=`<div class="card" style="padding:15px 18px"><span class="datechip">📅 ${DB.fecha}</span><h3 style="padding-right:120px">Precio de carga (kWh) — ${amb}</h3><div class="subtitle">Según ${fint(pr.length)} conectores con tarifa publicada en la selección.</div><div class="grid g3"><div style="background:#ECFDF5;border:1px solid #BBF7D0;border-radius:12px;padding:13px 16px"><div style="font-size:12px;color:#16A34A;font-weight:700">PRECIO MÍNIMO</div><div style="font-size:26px;font-weight:800">$${fint(mn)}<small style="font-size:12px;color:var(--muted);font-weight:700"> /kWh</small></div></div><div style="background:#EFF6FF;border:1px solid #BFDBFE;border-radius:12px;padding:13px 16px"><div style="font-size:12px;color:#2563EB;font-weight:700">PRECIO PROMEDIO</div><div style="font-size:26px;font-weight:800">$${fint(av)}<small style="font-size:12px;color:var(--muted);font-weight:700"> /kWh</small></div></div><div style="background:#FEF2F2;border:1px solid #FECACA;border-radius:12px;padding:13px 16px"><div style="font-size:12px;color:#EF4444;font-weight:700">PRECIO MÁXIMO</div><div style="font-size:26px;font-weight:800">$${fint(mx)}<small style="font-size:12px;color:var(--muted);font-weight:700"> /kWh</small></div></div></div><div class="card-src">Fuente: SEC, tarifas publicadas por operador · ${DB.fecha}</div></div>`;
  }else{pe.innerHTML=`<div class="card" style="padding:14px 18px;color:var(--muted);font-size:13px">Sin tarifas publicadas para la selección actual.</div>`;}}}
function tabInfraMapa(){const D=infraData(),f=F.infra;
  setTimeout(()=>{const m=leaflet('if-map',f.region?undefined:[-35.5,-71.3]);const col=c=>({AC_lenta:'#16A34A',AC_semi:'#2563EB',DC:'#EF4444'})[velOf(c)];const pts=[];D.forEach(c=>{if(!c.lat||!c.lng)return;pts.push([c.lat,c.lng]);L.circleMarker([c.lat,c.lng],{radius:3.2,color:col(c),fillColor:col(c),fillOpacity:.75,weight:0}).bindPopup(`<b>${c.c||''}</b><br>${c.r||''}<br>${c.kw||'?'} kW · ${c.t||''}`).addTo(m);});if(f.region&&pts.length){try{m.fitBounds(pts,{padding:[25,25],maxZoom:11})}catch(e){}}},60);
  return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Mapa interactivo — Conectores públicos</h3><div class="subtitle">${fint(D.length)} puntos en ${f.region||'todo Chile'}. Color por velocidad de carga.</div><div id="if-map" style="height:480px;border-radius:12px;border:1px solid var(--line)"></div><div style="display:flex;gap:18px;margin-top:10px;font-size:12.5px;flex-wrap:wrap"><span class="legrow"><i class="dot" style="background:#16A34A"></i> AC lenta (≤7 kW)</span><span class="legrow"><i class="dot" style="background:#2563EB"></i> AC semi (7–22 kW)</span><span class="legrow"><i class="dot" style="background:#EF4444"></i> DC rápida (≥50 kW)</span></div><div class="card-src">Fuente: SEC · ${DB.fecha}</div></div>`;}
function tabInfraTech(){const D=infraData();const v={AC_lenta:0,AC_semi:0,DC:0};D.forEach(c=>v[velOf(c)]++);
  setTimeout(()=>{const ctx=$('#if-donut');if(ctx)chart(ctx,{type:'doughnut',data:{labels:['AC lenta','AC semi','DC rápida'],datasets:[{data:[v.AC_lenta,v.AC_semi,v.DC],backgroundColor:['#16A34A','#2563EB','#EF4444'],borderWidth:0}]},options:{cutout:'64%',plugins:{legend:{display:false}},maintainAspectRatio:false}});},60);
  const tot=D.length||1;
  return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Conectores por velocidad de carga</h3><div class="subtitle">Mix tecnológico de la red en ${F.infra.region||'todo Chile'}.</div><div class="grid g2" style="align-items:center"><div style="position:relative;height:240px"><canvas id="if-donut"></canvas></div><div>${[['#16A34A','AC lenta ≤7 kW',v.AC_lenta],['#2563EB','AC semi 7–22 kW',v.AC_semi],['#EF4444','DC ≥50 kW',v.DC]].map(([c,n,val])=>`<div class="legrow" style="padding:8px 0;border-bottom:1px solid var(--line)"><i class="dot" style="background:${c}"></i><span class="nm">${n}</span><span class="vl">${fint(val)} · ${(val/tot*100).toFixed(0)}%</span></div>`).join('')}</div></div><div class="card-src">Fuente: SEC · ${DB.fecha}</div></div>`;}
function tabInfraOper(){const D=infraData();const op={};D.forEach(c=>{if(c.op)op[c.op]=(op[c.op]||0)+1;});let arr=Object.entries(op).sort((a,b)=>b[1]-a[1]);const top=arr.slice(0,5),ot=arr.slice(5).reduce((a,x)=>a+x[1],0),tot=arr.reduce((a,x)=>a+x[1],0)||1;const rows=[...top];if(ot>0)rows.push(['Otros',ot]);
  return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Ranking de operadores</h3><div class="subtitle">Participación por número de conectores · ${F.infra.region||'todo Chile'}.</div>${rows.length?rankRows(rows,v=>fint(v)+' · '+(v/tot*100).toFixed(1)+'%'):'<p style="color:var(--muted)">Sin operadores en la selección.</p>'}<div class="card-src">Fuente: SEC, clasificación por instalador · ${DB.fecha}</div></div>`;}

function precioCard(g,carga,col){const loc=x=>`${x.sitio}<br><span style="color:var(--muted)">${x.comuna}, ${x.region}</span>`;
  return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Precio carga ${carga} <span style="font-weight:600;color:var(--muted);font-size:13px">· nacional</span></h3><div class="subtitle">Según ${fint(g.n)} conectores ${carga} con tarifa publicada. Promedio $${fint(g.avg)}/kWh.</div>
   <div class="grid g2" style="margin-top:6px">
     <div style="background:#ECFDF5;border:1px solid #BBF7D0;border-radius:12px;padding:15px 16px"><div style="font-size:11.5px;color:#16A34A;font-weight:800">PRECIO MÍNIMO</div><div style="font-size:30px;font-weight:800;color:#16A34A">$${fint(g.min.precio)}<small style="font-size:12px;color:var(--muted);font-weight:700"> /kWh</small></div>
       <div style="margin-top:8px;font-size:12px"><b>📍 Ubicación:</b><br>${loc(g.min)}</div>
       <div style="margin-top:6px;font-size:12px"><b>⚡ Potencia:</b> ${fint(g.min.kw)} kW · ${g.min.conector||'—'}</div></div>
     <div style="background:#FEF2F2;border:1px solid #FECACA;border-radius:12px;padding:15px 16px"><div style="font-size:11.5px;color:#EF4444;font-weight:800">PRECIO MÁXIMO</div><div style="font-size:30px;font-weight:800;color:#EF4444">$${fint(g.max.precio)}<small style="font-size:12px;color:var(--muted);font-weight:700"> /kWh</small></div>
       <div style="margin-top:8px;font-size:12px"><b>📍 Ubicación:</b><br>${loc(g.max)}</div>
       <div style="margin-top:6px;font-size:12px"><b>⚡ Potencia:</b> ${fint(g.max.kw)} kW · ${g.max.conector||'—'}</div></div>
   </div><div class="card-src">Fuente: SEC, tarifas publicadas por operador · ${DB.fecha}</div></div>`;}
function tabInfraPrecios(){const P=DATA.precios_acdc;
  return `<div style="display:grid;gap:16px">${precioCard(P.ac,'AC','#16A34A')}${precioCard(P.dc,'DC','#EF4444')}</div>
   <div class="insight"><div class="ic">i</div><div><b>Lectura ejecutiva.</b> La carga AC pública va de $${fint(P.ac.min.precio)} (${P.ac.min.comuna}) a $${fint(P.ac.max.precio)} (${P.ac.max.comuna}) por kWh. La carga rápida DC, de $${fint(P.dc.min.precio)} (${P.dc.min.comuna}) a $${fint(P.dc.max.precio)} (${P.dc.max.comuna}). Cada precio indica el sitio y la potencia del conector.</div></div>`;}

/* ===== MERCADO EV (tabs) ===== */
const TECHS=['BEV','PHEV','HEV','MHEV','EBUS','ETRUCK'];
async function pageMercado(){const M=await load('mercado');await load('mercado_extra');F.merc=F.merc||{anio:'',tech:'',q:'',orden:'anio'};TAB.merc=TAB.merc||'ventas';
  const anios=[...new Set(M.meses.map(m=>m.slice(0,4)))].sort();
  return `<div class="page-head"><h1>Mercado EV</h1><p class="sub">Ventas mensuales, penetración por tecnología y catálogo de marcas y modelos.</p></div>
   <div class="filterbar"><div class="fgroup"><label>Año</label><select id="mf-anio"><option value="">Todos</option>${fopt(anios,F.merc.anio)}</select></div><div class="fgroup"><label>Tecnología</label><select id="mf-tech"><option value="">Todas</option>${TECHS.map(t=>`<option value="${t}"${F.merc.tech===t?' selected':''}>${t}</option>`).join('')}</select></div><button class="btn btn-ghost" id="mf-reset" style="align-self:flex-end">Limpiar filtros</button></div>
   <div class="grid g4" id="mc-kpis" style="margin-bottom:18px"></div>
   ${tabsNav('merc',[{id:'ventas',label:'Ventas'},{id:'tech',label:'Tecnología'},{id:'marcas',label:'Marcas'},{id:'region',label:'Por región'},{id:'buscador',label:'Buscador de modelos'}])}`;}
function mercMeses(){const M=DATA.mercado,f=F.merc;return f.anio?M.serie.filter(s=>s.mes.startsWith(f.anio)):M.serie;}
function bindMercado(){const re=()=>{mercKpis();renderTab('merc');};$('#mf-anio').onchange=e=>{F.merc.anio=e.target.value;re();};$('#mf-tech').onchange=e=>{F.merc.tech=e.target.value;re();};$('#mf-reset').onclick=()=>{F.merc={anio:'',tech:'',q:'',orden:'anio'};$('#mf-anio').value='';$('#mf-tech').value='';re();};}
function mercKpis(){const M=DATA.mercado,f=F.merc,meses=mercMeses();const techs=f.tech?[f.tech]:TECHS;const ult=M.serie.at(-1);const ench=(ult.bev||0)+(ult.phev||0);const acum=meses.reduce((a,s)=>a+techs.reduce((x,t)=>x+(s[t.toLowerCase()]||0),0),0);const marcasAct=M.marcas.filter(m=>m.a2026>0).length;
  const el=$('#mc-kpis');if(el)el.innerHTML=[kpi({lbl:'Enchufables último mes (BEV+PHEV)',val:fint(ench),bg:'#EFF6FF',c:'#2563EB',icon:IC.car}),kpi({lbl:(f.tech||'Total')+' en el periodo',val:fint(acum),unit:'u',bg:'#ECFDF5',c:'#16A34A',icon:IC.bolt}),kpi({lbl:'Marcas activas (2026)',val:fint(marcasAct),bg:'#FEF3C7',c:'#F59E0B',icon:IC.target}),kpi({lbl:'Modelos homologados',val:fint(M.homol.length),bg:'#F3E8FF',c:'#7C3AED',icon:IC.doc})].join('');}
function tabMercVentas(){const f=F.merc,meses=mercMeses();const techs=f.tech?[f.tech]:TECHS;const last=meses.slice(-12);const labels=last.map(s=>s.mes.slice(2));const ds=techs.map(t=>({label:t,data:last.map(s=>s[t.toLowerCase()]||0),backgroundColor:COLS[t],borderWidth:0}));
  setTimeout(()=>{const cx=$('#mc-chart');if(cx)chart(cx,{type:'bar',data:{labels,datasets:ds},options:{responsive:true,maintainAspectRatio:false,scales:{x:{stacked:true,ticks:{font:{size:10}}},y:{stacked:true}},plugins:{legend:{position:'bottom',labels:{boxWidth:12,font:{size:11}}}}}});},60);
  const rango=last.length?`${last[0].mes} a ${last.at(-1).mes}`:'';
  return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Ventas mensuales por tecnología</h3><div class="subtitle">${f.anio?'Año '+f.anio:'Últimos 12 meses'} · ${rango}.</div><div style="position:relative;height:320px"><canvas id="mc-chart"></canvas></div><div class="card-src">Fuente: ANAC · ventas de vehículos eléctricos Chile mensual · ${DB.fecha}</div></div>`;}
function tabMercTech(){const meses=mercMeses();const mix=TECHS.map(t=>meses.reduce((a,s)=>a+(s[t.toLowerCase()]||0),0));const tot=mix.reduce((a,b)=>a+b,0)||1;
  setTimeout(()=>{const dc=$('#mc-donut');if(dc)chart(dc,{type:'doughnut',data:{labels:TECHS,datasets:[{data:mix,backgroundColor:TECHS.map(t=>COLS[t]),borderWidth:0}]},options:{cutout:'62%',plugins:{legend:{display:false}},maintainAspectRatio:false}});},60);
  return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Mix tecnológico</h3><div class="subtitle">Participación por tecnología ${F.merc.anio?'· año '+F.merc.anio:'· periodo completo'}.</div><div class="grid g2" style="align-items:center"><div style="position:relative;height:250px"><canvas id="mc-donut"></canvas></div><div>${TECHS.map((t,i)=>`<div class="legrow" style="padding:7px 0;border-bottom:1px solid var(--line)"><i class="dot" style="background:${COLS[t]}"></i><span class="nm">${t}</span><span class="vl">${fint(mix[i])} · ${(mix[i]/tot*100).toFixed(0)}%</span></div>`).join('')}</div></div><div class="card-src">Fuente: ANAC · ${DB.fecha}</div></div>`;}
function tabMercMarcas(){const M=DATA.mercado,f=F.merc;let mk=[...M.marcas];const vget=m=>f.tech==='BEV'?m.bev:f.tech==='PHEV'?m.phev:m.a2026;mk.sort((a,b)=>vget(b)-vget(a));mk=mk.filter(m=>vget(m)>0).slice(0,12);
  return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Ranking de marcas</h3><div class="subtitle">${f.tech?`Top marcas ${f.tech} (último mes)`:'Top marcas por unidades acumuladas 2026'}.</div>${rankRows(mk.map(m=>[m.marca,vget(m)]),v=>fint(v)+' u')}<div class="card-src">Fuente: ANAC · marcas de EVs por mes · ${DB.fecha}</div></div>`;}
function tabMercBuscador(){
  setTimeout(()=>{const inp=$('#mc-q');if(inp){let t;inp.oninput=e=>{F.merc.q=e.target.value;clearTimeout(t);t=setTimeout(renderBuscador,160);};inp.value=F.merc.q||'';}const ord=$('#mc-orden');if(ord)ord.onchange=e=>{F.merc.orden=e.target.value;renderBuscador();};renderBuscador();},60);
  return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Buscador de vehículos — marca y modelo</h3><div class="subtitle">${fint(DATA.mercado.homol.length)} modelos homologados. Filtra por tecnología arriba; ordena por año, modelo o tecnología.</div>
   <div class="filterbar" style="box-shadow:none;border:none;padding:6px 0;margin:4px 0"><div class="fgroup" style="flex:1"><label>Buscar marca o modelo</label><input id="mc-q" type="text" placeholder="Ej: BYD, Tesla, Dolphin…" style="padding:9px 12px;border:1.5px solid var(--line);border-radius:9px;font-size:13.5px"></div><div class="fgroup"><label>Ordenar por</label><select id="mc-orden"><option value="anio">Año (desc)</option><option value="modelo">Modelo (A-Z)</option><option value="tech">Tecnología</option></select></div></div>
   <div id="mc-busca"></div><div class="card-src">Fuente: ANAC · vehículos homologados y ficha de seguridad · ${DB.fecha}</div></div>`;}
function renderBuscador(){const M=DATA.mercado,f=F.merc,q=norm(f.q);let rows=M.homol.map(h=>({marca:h[0],modelo:h[1],tech:h[2],carr:h[3],anio:h[4],seg:h[7]}));if(f.tech)rows=rows.filter(r=>r.tech===f.tech);if(q)rows=rows.filter(r=>norm(r.marca).includes(q)||norm(r.modelo).includes(q));
  if(f.orden==='modelo')rows.sort((a,b)=>a.modelo.localeCompare(b.modelo));else if(f.orden==='tech')rows.sort((a,b)=>(''+a.tech).localeCompare(''+b.tech)||(''+b.anio).localeCompare(''+a.anio));else rows.sort((a,b)=>(''+b.anio).localeCompare(''+a.anio));
  const el=$('#mc-busca');if(!el)return;if(!q&&!f.tech){el.innerHTML='<p style="color:var(--muted);padding:8px 0">Escribe una marca o modelo para ver resultados.</p>';return;}
  const tc={BEV:'#2563EB',PHEV:'#16A34A',HEV:'#F59E0B',MHEV:'#7C3AED'};
  el.innerHTML=`<div style="font-size:12px;color:var(--muted);margin-bottom:8px">${fint(rows.length)} resultados${rows.length>60?' (mostrando 60)':''}</div><div class="grid" style="grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:10px">${rows.slice(0,60).map(r=>`<div style="border:1px solid var(--line);border-radius:11px;padding:11px 13px"><div style="display:flex;justify-content:space-between;gap:8px;align-items:start"><b style="font-size:13.5px">${r.marca}</b><span style="font-size:10.5px;font-weight:700;color:#fff;background:${tc[r.tech]||'#64748B'};padding:2px 7px;border-radius:10px">${r.tech}</span></div><div style="font-size:12.5px;margin-top:3px">${r.modelo}</div><div style="font-size:11.5px;color:var(--muted);margin-top:4px">${r.carr||''} · ${r.anio||''}${r.seg?` · ⭐ ${r.seg}`:''}</div></div>`).join('')}</div>`;}

/* ===== ENERGÍA (tabs) ===== */
const ESTADOS=['En Operación','En Construcción','Aprobado','En Calificación','En Pruebas'];
async function pageEnergia(){const E=await load('energia');await load('energia_extra');F.ener=F.ener||{region:'',estado:'',fuente:''};TAB.ener=TAB.ener||'mapa';
  const fuentes=[...new Set(E.mapa.map(p=>p.t))].filter(Boolean).sort();
  return `<div class="page-head"><h1>Energía y BESS</h1><p class="sub">Generación renovable, almacenamiento y ubicación de proyectos energéticos.</p></div>
   <div class="filterbar"><div class="fgroup"><label>Región</label><select id="ef-reg"><option value="">Todo Chile</option>${fopt(REGS(),F.ener.region)}</select></div><div class="fgroup"><label>Estado</label><select id="ef-est"><option value="">Todos</option>${ESTADOS.map(s=>`<option value="${s}"${F.ener.estado===s?' selected':''}>${s}</option>`).join('')}</select></div><div class="fgroup"><label>Fuente / Tecnología</label><select id="ef-fue"><option value="">Todas</option>${fuentes.map(s=>`<option value="${s}"${F.ener.fuente===s?' selected':''}>${s}</option>`).join('')}</select></div><button class="btn btn-ghost" id="ef-reset" style="align-self:flex-end">Limpiar filtros</button></div>
   <div class="grid g4" id="en-kpis" style="margin-bottom:18px"></div>
   ${tabsNav('ener',[{id:'mapa',label:'Mapa de proyectos'},{id:'fuente',label:'Por fuente'},{id:'region',label:'Por región'},{id:'bess',label:'BESS'},{id:'solar',label:'Solar'}])}`;}
function enerData(){const E=DATA.energia,f=F.ener;const mr=pr=>!f.region||norm(pr)===norm(f.region)||norm(pr).includes(norm(f.region));return E.mapa.filter(p=>mr(p.r)&&(!f.estado||p.e===f.estado)&&(!f.fuente||p.t===f.fuente));}
function fuenteCol(t){t=(t||'').toLowerCase();if(t.includes('solar'))return'#F59E0B';if(t.includes('eól')||t.includes('eol'))return'#0EA5E9';if(t.includes('bess')||t.includes('bater'))return'#7C3AED';return'#16A34A';}
function bindEnergia(){const re=()=>{enerKpis();renderTab('ener');};$('#ef-reg').onchange=e=>{F.ener.region=e.target.value;re();};$('#ef-est').onchange=e=>{F.ener.estado=e.target.value;re();};$('#ef-fue').onchange=e=>{F.ener.fuente=e.target.value;re();};$('#ef-reset').onclick=()=>{F.ener={region:'',estado:'',fuente:''};$('#ef-reg').value='';$('#ef-est').value='';$('#ef-fue').value='';re();};}
function enerKpis(){const E=DATA.energia,D=enerData();const op=D.filter(p=>p.e==='En Operación');const mwOp=op.reduce((a,p)=>a+(+p.mw||0),0);const mwTot=D.reduce((a,p)=>a+(+p.mw||0),0);const bess=D.filter(p=>(p.t||'').toLowerCase().includes('bess'));
  const el=$('#en-kpis');if(el)el.innerHTML=[kpi({lbl:'MW renovables (operativos)',val:fint(mwOp),unit:'MW',bg:'#FEF9C3',c:'#CA8A04',icon:IC.sun}),kpi({lbl:'MW en cartera (selección)',val:fint(mwTot),unit:'MW',bg:'#EFF6FF',c:'#2563EB',icon:IC.bolt}),kpi({lbl:'Proyectos',val:fint(D.length),bg:'#ECFDF5',c:'#16A34A',icon:IC.target}),kpi({lbl:'Proyectos BESS',val:fint(bess.length),bg:'#F3E8FF',c:'#7C3AED',icon:IC.bat})].join('');}
function tabEnerMapa(){const E=DATA.energia,D=enerData(),f=F.ener;const op=D.filter(p=>p.e==='En Operación');const mwOp=op.reduce((a,p)=>a+(+p.mw||0),0);
  let note;if(!f.region&&!f.estado&&!f.fuente){const fMW=Math.max(E.totales.mwOperativo-mwOp,0),fN=Math.max(E.totales.proyectosOp-op.length,0);note=`<b>Cobertura del mapa.</b> Del total oficial de ${fint(E.totales.mwOperativo)} MW renovables operativos (CEN · ${fint(E.totales.proyectosOp)} proyectos), el mapa georreferencia ${fint(mwOp)} MW (${fint(op.length)} proyectos). Faltan por sumar <b>${fint(fMW)} MW</b> (~${fint(fN)} proyectos) que aún no tienen ubicación georreferenciada disponible.`;}else{note=`Mostrando proyectos georreferenciados de la selección. Pueden existir proyectos adicionales sin coordenadas publicadas.`;}
  setTimeout(()=>{const m=leaflet('en-map',f.region?undefined:[-35.5,-71.3]);const pts=[];D.forEach(p=>{if(!p.lat||!p.lng)return;pts.push([p.lat,p.lng]);const rad=Math.max(3,Math.min(14,Math.sqrt((+p.mw||1))/2.2));L.circleMarker([p.lat,p.lng],{radius:rad,color:fuenteCol(p.t),fillColor:fuenteCol(p.t),fillOpacity:.55,weight:1}).bindPopup(`<b>${p.n||''}</b><br>${p.t||''}<br>${p.r||''}<br>${fint(p.mw)} MW · ${p.e||''}`).addTo(m);});if(f.region&&pts.length){try{m.fitBounds(pts,{padding:[25,25],maxZoom:9})}catch(e){}}},60);
  return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Mapa de proyectos energéticos</h3><div class="subtitle">${fint(D.length)} proyectos en ${f.region||'todo Chile'}. Tamaño según capacidad (MW).</div><div id="en-map" style="height:460px;border-radius:12px;border:1px solid var(--line)"></div><div style="display:flex;gap:16px;margin-top:10px;font-size:12.5px;flex-wrap:wrap"><span class="legrow"><i class="dot" style="background:#F59E0B"></i> Solar</span><span class="legrow"><i class="dot" style="background:#0EA5E9"></i> Eólica</span><span class="legrow"><i class="dot" style="background:#7C3AED"></i> BESS</span><span class="legrow"><i class="dot" style="background:#16A34A"></i> Otra</span></div><div style="margin-top:11px;background:#FFFBEB;border:1px solid #FDE68A;border-radius:11px;padding:11px 14px;font-size:12.5px;color:#92400E;line-height:1.5">${note}</div><div class="card-src">Fuente: Coordinador Eléctrico Nacional (CEN) · SEIA · ${DB.fecha}</div></div>`;}
function tabEnerFuente(){const D=enerData();const byF={};D.forEach(p=>{const k=p.t||'Otra';byF[k]=(byF[k]||0)+(+p.mw||0);});let fe=Object.entries(byF).sort((a,b)=>b[1]-a[1]).slice(0,8);const tot=fe.reduce((a,x)=>a+x[1],0)||1;
  setTimeout(()=>{const dc=$('#en-donut');if(dc)chart(dc,{type:'doughnut',data:{labels:fe.map(x=>x[0]),datasets:[{data:fe.map(x=>Math.round(x[1])),backgroundColor:fe.map(x=>fuenteCol(x[0])),borderWidth:0}]},options:{cutout:'60%',plugins:{legend:{display:false}},maintainAspectRatio:false}});},60);
  return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Capacidad por fuente</h3><div class="subtitle">MW por tecnología · ${F.ener.region||'todo Chile'}.</div><div class="grid g2" style="align-items:center"><div style="position:relative;height:250px"><canvas id="en-donut"></canvas></div><div>${fe.map(x=>`<div class="legrow" style="padding:7px 0;border-bottom:1px solid var(--line)"><i class="dot" style="background:${fuenteCol(x[0])}"></i><span class="nm">${x[0]}</span><span class="vl">${fint(x[1])} MW · ${(x[1]/tot*100).toFixed(0)}%</span></div>`).join('')}</div></div><div class="card-src">Fuente: CEN · ${DB.fecha}</div></div>`;}
function tabEnerRegion(){const D=enerData();const byR={};D.forEach(p=>{if(p.e==='En Operación'){const k=p.r||'—';byR[k]=(byR[k]||0)+(+p.mw||0);}});let rr=Object.entries(byR).sort((a,b)=>b[1]-a[1]).slice(0,12);
  return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Ranking de potencia por región</h3><div class="subtitle">MW renovables operativos.</div>${rr.length?rankRows(rr,v=>fint(v)+' MW'):'<p style="color:var(--muted)">Sin proyectos operativos en la selección.</p>'}<div class="card-src">Fuente: CEN · ${DB.fecha}</div></div>`;}

/* ===== INVERSIÓN (tabs + mapa de brechas) ===== */
async function pageInversion(){const I=await load('inversion');F.inv=F.inv||{region:'',prio:''};TAB.inv=TAB.inv||'mapa';
  return `<div class="page-head"><h1>Oportunidades de Inversión</h1><p class="sub">Brechas de cobertura priorizadas: dónde falta carga pública y con qué urgencia.</p></div>
   <div class="filterbar"><div class="fgroup"><label>Región</label><select id="vf-reg"><option value="">Todo Chile</option>${fopt(REGS(),F.inv.region)}</select></div><div class="fgroup"><label>Prioridad</label><select id="vf-prio"><option value="">Todas</option><option value="ALTA"${F.inv.prio==='ALTA'?' selected':''}>Alta</option><option value="MEDIA"${F.inv.prio==='MEDIA'?' selected':''}>Media</option><option value="BAJA"${F.inv.prio==='BAJA'?' selected':''}>Baja</option></select></div><button class="btn btn-ghost" id="vf-reset" style="align-self:flex-end">Limpiar filtros</button></div>
   <div class="grid g4" id="iv-kpis" style="margin-bottom:18px"></div>
   ${tabsNav('inv',[{id:'mapa',label:'Mapa de brechas'},{id:'cobertura',label:'Cobertura'},{id:'ranking',label:'Ranking'}])}`;}
function invData(){const I=DATA.inversion,f=F.inv;return I.gaps.filter(g=>(!f.region||g.region===f.region)&&(!f.prio||g.prioridad===f.prio));}
function bindInversion(){const re=()=>{invKpis();renderTab('inv');};$('#vf-reg').onchange=e=>{F.inv.region=e.target.value;re();};$('#vf-prio').onchange=e=>{F.inv.prio=e.target.value;re();};$('#vf-reset').onclick=()=>{F.inv={region:'',prio:''};$('#vf-reg').value='';$('#vf-prio').value='';re();};}
const prioCol=p=>p==='ALTA'?'#EF4444':p==='MEDIA'?'#F59E0B':'#16A34A';
function invKpis(){const I=DATA.inversion,D=invData();const alta=D.filter(g=>g.prioridad==='ALTA').length;const kwt=D.reduce((a,g)=>a+(+g.kw_recom||0),0);
  const el=$('#iv-kpis');if(el)el.innerHTML=[kpi({lbl:'Brechas detectadas',val:fint(D.length),bg:'#FEE2E2',c:'#EF4444',icon:IC.target}),kpi({lbl:'Prioridad alta',val:fint(alta),bg:'#FEF3C7',c:'#F59E0B',icon:IC.bolt}),kpi({lbl:'Comunas sin carga',val:fint(I.cobertura.sin),unit:'/ '+I.cobertura.total,bg:'#EFF6FF',c:'#2563EB',icon:IC.map}),kpi({lbl:'Potencia recomendada',val:fint(kwt/1000),unit:'MW',bg:'#F3E8FF',c:'#7C3AED',icon:IC.plug})].join('');}
function tabInvMapa(){const D=invData(),f=F.inv;
  setTimeout(()=>{const m=leaflet('iv-map',f.region?undefined:[-35.5,-71.3]);const pts=[];D.forEach(g=>{if(!g.lat||!g.lng)return;pts.push([g.lat,g.lng]);L.circleMarker([g.lat,g.lng],{radius:6,color:prioCol(g.prioridad),fillColor:prioCol(g.prioridad),fillOpacity:.6,weight:1.5}).bindPopup(`<b>${g.lugar}</b><br>${g.region}<br>Dist. cargador: ${fmt(g.dist_cercano)} km<br>Recom.: ${fint(g.kw_recom)} kW · ${g.prioridad}`).addTo(m);});if(f.region&&pts.length){try{m.fitBounds(pts,{padding:[30,30],maxZoom:8})}catch(e){}}},60);
  return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Mapa de brechas priorizadas</h3><div class="subtitle">${fint(D.length)} localidades en ${f.region||'todo Chile'}. Color por prioridad.</div><div id="iv-map" style="height:480px;border-radius:12px;border:1px solid var(--line)"></div><div style="display:flex;gap:18px;margin-top:10px;font-size:12.5px;flex-wrap:wrap"><span class="legrow"><i class="dot" style="background:#EF4444"></i> Prioridad alta</span><span class="legrow"><i class="dot" style="background:#F59E0B"></i> Media</span><span class="legrow"><i class="dot" style="background:#16A34A"></i> Baja</span></div><div class="card-src">Fuente: análisis EV · SEC + distancias viales · ${DB.fecha}</div></div>`;}
function tabInvCobertura(){const I=DATA.inversion,D=invData();const a=D.filter(g=>g.prioridad==='ALTA').length,me=D.filter(g=>g.prioridad==='MEDIA').length,b=D.filter(g=>g.prioridad==='BAJA').length;const mxp=Math.max(a,me,b,1);
  setTimeout(()=>{const dc=$('#iv-donut');if(dc)chart(dc,{type:'doughnut',data:{labels:['Con carga','Sin carga'],datasets:[{data:[I.cobertura.con,I.cobertura.sin],backgroundColor:['#16A34A','#EF4444'],borderWidth:0}]},options:{cutout:'64%',plugins:{legend:{display:false}},maintainAspectRatio:false}});},60);
  return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Cobertura nacional y prioridades</h3><div class="subtitle">Comunas con y sin carga pública · distribución de brechas.</div><div class="grid g2" style="align-items:center"><div style="position:relative;height:230px"><canvas id="iv-donut"></canvas></div><div><div class="legrow" style="padding:7px 0;border-bottom:1px solid var(--line)"><i class="dot" style="background:#16A34A"></i><span class="nm">Comunas con carga</span><span class="vl">${fint(I.cobertura.con)}</span></div><div class="legrow" style="padding:7px 0;border-bottom:1px solid var(--line)"><i class="dot" style="background:#EF4444"></i><span class="nm">Comunas sin carga</span><span class="vl">${fint(I.cobertura.sin)}</span></div>${[['Alta',a,'#EF4444'],['Media',me,'#F59E0B'],['Baja',b,'#16A34A']].map(([n,v,c])=>`<div class="rank" style="padding:7px 0"><div class="legrow"><span class="nm">Prioridad ${n}</span><span class="vl">${fint(v)} brechas</span></div><div class="bar"><i style="width:${(v/mxp*100).toFixed(0)}%;background:${c}"></i></div></div>`).join('')}</div></div><div class="card-src">Fuente: SEC · análisis EV · ${DB.fecha}</div></div>`;}
function tabInvRanking(){const D=invData();const rows=[...D].sort((a,b)=>(b.dist_cercano||0)-(a.dist_cercano||0)).slice(0,20);
  return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Ranking de brechas priorizadas</h3><div class="subtitle">Localidades con mayor distancia al cargador más cercano.</div><div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse;font-size:13px"><thead><tr style="text-align:left;color:var(--muted);font-size:11.5px;text-transform:uppercase"><th style="padding:8px 6px">#</th><th style="padding:8px 6px">Localidad</th><th style="padding:8px 6px">Región</th><th style="padding:8px 6px;text-align:right">Dist. (km)</th><th style="padding:8px 6px;text-align:right">kW rec.</th><th style="padding:8px 6px;text-align:center">Prioridad</th></tr></thead><tbody>${rows.map((g,i)=>`<tr style="border-top:1px solid var(--line)"><td style="padding:8px 6px;color:var(--muted)">${i+1}</td><td style="padding:8px 6px;font-weight:700">${g.lugar}</td><td style="padding:8px 6px">${g.region}</td><td style="padding:8px 6px;text-align:right">${fmt(g.dist_cercano)}</td><td style="padding:8px 6px;text-align:right">${fint(g.kw_recom)}</td><td style="padding:8px 6px;text-align:center"><span style="font-size:10.5px;font-weight:700;color:#fff;background:${prioCol(g.prioridad)};padding:2px 8px;border-radius:10px">${g.prioridad}</span></td></tr>`).join('')}</tbody></table></div><div class="card-src">Fuente: análisis EV · SEC + distancias viales · ${DB.fecha}</div></div>`;}

/* ===== REPORTES (tabs: ficha + mapa) ===== */
async function pageReportes(){await Promise.all([load('reportes').then(d=>REP=d),load('coords').then(d=>COORDS=d)]);DATA.reportes=REP;F.rep=F.rep||{region:'',comuna:''};TAB.rep=TAB.rep||'ficha';
  const coms=F.rep.region?REP.com.filter(c=>c.r===F.rep.region).map(c=>c.c).sort((a,b)=>a.localeCompare(b)):[];
  return `<div class="page-head"><h1>Reportes Regionales & Comunales</h1><p class="sub">Selecciona una región y comuna para ver su ficha completa.</p></div>
   <div class="filterbar"><div class="fgroup"><label>Región</label><select id="rf-reg"><option value="">Selecciona región…</option>${fopt(REGS(),F.rep.region)}</select></div><div class="fgroup"><label>Comuna</label><select id="rf-com"><option value="">Toda la región</option>${coms.map(c=>`<option value="${c}"${F.rep.comuna===c?' selected':''}>${c}</option>`).join('')}</select></div><button class="btn btn-ghost" id="rf-reset" style="align-self:flex-end">Limpiar</button></div>
   ${tabsNav('rep',[{id:'ficha',label:'Ficha'},{id:'mapa',label:'Mapa'}])}`;}
function bindReportes(){$('#rf-reg').onchange=e=>{F.rep.region=e.target.value;F.rep.comuna='';const coms=REP.com.filter(c=>c.r===F.rep.region).map(c=>c.c).sort((a,b)=>a.localeCompare(b));$('#rf-com').innerHTML='<option value="">Toda la región</option>'+coms.map(c=>`<option value="${c}">${c}</option>`).join('');renderTab('rep');};$('#rf-com').onchange=e=>{F.rep.comuna=e.target.value;renderTab('rep');};$('#rf-reset').onclick=()=>{F.rep={region:'',comuna:''};$('#rf-reg').value='';$('#rf-com').innerHTML='<option value="">Toda la región</option>';renderTab('rep');};}
function tabRepFicha(){const f=F.rep;if(!f.region)return '<div class="card soon"><div class="big">📍</div><h3>Selecciona una región</h3><p style="margin-top:6px">Elige una región (y opcionalmente comuna) para ver su ficha.</p></div>';
  if(f.comuna){const c=REP.com.find(x=>x.c===f.comuna&&x.r===f.region);if(!c)return '<p>Sin datos.</p>';
    return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>${c.c} <span style="font-weight:600;color:var(--muted);font-size:14px">· ${c.r}</span></h3><div class="grid g4" style="margin-top:14px">${ind('Población',fint(c.p))}${ind('Vehículos eléctricos',fint(c.e))}${ind('Conectores públicos',fint(c.k))}${ind('Cargadores DC',fint(c.d))}</div><div class="grid g4" style="margin-top:12px">${ind('Potencia máx.',fint(c.kw),'kW')}${ind('EV por 1.000 hab.',(''+c.e1).replace('.',','))}${ind('Ratio EV/conector',(''+c.rt).replace('.',','))}${ind('Conectores /10mil hab',(''+c.c10).replace('.',','))}</div>${c.pr?`<div style="margin-top:16px"><h3 style="font-size:14px;padding-right:0">Precio de carga (kWh)</h3><div class="grid g2" style="margin-top:10px"><div style="background:#ECFDF5;border:1px solid #BBF7D0;border-radius:12px;padding:13px 15px"><div style="font-size:12px;color:#16A34A;font-weight:700">PRECIO MÍNIMO</div><div style="font-size:22px;font-weight:800">$${c.pr.min}<small style="font-size:12px;color:var(--muted)"> /kWh</small></div><div style="font-size:11.5px;color:var(--muted);margin-top:4px">${c.pr.mindesc||''}<br>${c.pr.minloc||''}</div></div><div style="background:#FEF2F2;border:1px solid #FECACA;border-radius:12px;padding:13px 15px"><div style="font-size:12px;color:#EF4444;font-weight:700">PRECIO MÁXIMO</div><div style="font-size:22px;font-weight:800">$${c.pr.max}<small style="font-size:12px;color:var(--muted)"> /kWh</small></div><div style="font-size:11.5px;color:var(--muted);margin-top:4px">${c.pr.maxdesc||''}<br>${c.pr.maxloc||''}</div></div></div></div>`:''}<div class="card-src">Fuente: SEC · INE Censo 2024 · permisos de circulación · ${DB.fecha}</div></div>`;}
  const rg=REP.reg[regKey(f.region)];if(!rg)return '<p>Sin datos regionales.</p>';
  return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Región de ${f.region}</h3><div class="grid g4" style="margin-top:14px">${ind('Comunas',fint(rg.comunas))}${ind('Población',fint(rg.pob))}${ind('Vehículos eléctricos',fint(rg.evs))}${ind('Conectores públicos',fint(rg.con))}</div><div class="grid g4" style="margin-top:12px">${ind('Cargadores DC',fint(rg.dc))}${ind('Comunas sin carga',fint(rg.sincarg))}${ind('EV por 1.000 hab.',(''+rg.evs_1000).replace('.',','))}${ind('Ratio EV/conector',(''+rg.ratio).replace('.',','))}</div><h3 style="font-size:14px;margin-top:18px;padding-right:0">Energía renovable</h3><div class="grid g4" style="margin-top:10px">${ind('ERNC operativa',fint(rg.ernc_mw),'MW')}${ind('Proyectos ERNC',fint(rg.ernc_n))}${ind('Solar',fint(rg.solar_mw),'MW')}${ind('Tráfico medio (TMDA)',fint(rg.tmda))}</div><div class="card-src">Fuente: SEC · CEN · INE Censo 2024 · MOP Vialidad · ${DB.fecha}</div></div>`;}
function tabRepMapa(){const f=F.rep;if(!f.region)return '<div class="card soon"><div class="big">🗺️</div><h3>Selecciona una región</h3><p style="margin-top:6px">El mapa mostrará los cargadores de la región o comuna elegida.</p></div>';
  const D=CARG.filter(c=>c.r===f.region&&(!f.comuna||norm(c.c)===norm(f.comuna)));
  setTimeout(()=>{let view;const rc=COORDS.region[f.region];const cc=f.comuna&&COORDS.comuna[norm(f.comuna)];view=cc||rc||[-35.5,-71.3];const m=leaflet('rep-map',view);m.setZoom(f.comuna?11:7);const col=c=>({AC_lenta:'#16A34A',AC_semi:'#2563EB',DC:'#EF4444'})[velOf(c)];const pts=[];D.forEach(c=>{if(!c.lat||!c.lng)return;pts.push([c.lat,c.lng]);L.circleMarker([c.lat,c.lng],{radius:4,color:col(c),fillColor:col(c),fillOpacity:.75,weight:0}).bindPopup(`<b>${c.c||''}</b><br>${c.kw||'?'} kW · ${c.t||''}`).addTo(m);});if(pts.length){try{m.fitBounds(pts,{padding:[30,30],maxZoom:f.comuna?13:9})}catch(e){}}},60);
  return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Mapa de carga — ${f.comuna||f.region}</h3><div class="subtitle">${fint(D.length)} conectores públicos. Color por velocidad de carga.</div><div id="rep-map" style="height:460px;border-radius:12px;border:1px solid var(--line)"></div><div style="display:flex;gap:18px;margin-top:10px;font-size:12.5px;flex-wrap:wrap"><span class="legrow"><i class="dot" style="background:#16A34A"></i> AC lenta</span><span class="legrow"><i class="dot" style="background:#2563EB"></i> AC semi</span><span class="legrow"><i class="dot" style="background:#EF4444"></i> DC rápida</span></div><div class="card-src">Fuente: SEC · ${DB.fecha}</div></div>`;}

/* ===== CALCULADORA (tabs: ranking, mapa, detalle) ===== */
async function pageCalc(){const C=await load('calc');await load('coords').then(d=>COORDS=d);F.calc=F.calc||{region:'',comuna:''};TAB.calc=TAB.calc||'ranking';
  const coms=F.calc.region?C.data.filter(d=>d.region===F.calc.region).map(d=>d.comuna).sort((a,b)=>a.localeCompare(b)):[];
  return `<div class="page-head"><h1>Calculadora de Oportunidades</h1><p class="sub">Score de oportunidad de inversión por comuna: flota EV, cobertura de carga y potencial.</p></div>
   <div class="filterbar"><div class="fgroup"><label>Región</label><select id="cf-reg"><option value="">Todo Chile</option>${fopt(REGS(),F.calc.region)}</select></div><div class="fgroup"><label>Comuna</label><select id="cf-com"><option value="">Todas</option>${coms.map(c=>`<option value="${c}"${F.calc.comuna===c?' selected':''}>${c}</option>`).join('')}</select></div><button class="btn btn-ghost" id="cf-reset" style="align-self:flex-end">Limpiar</button></div>
   ${tabsNav('calc',[{id:'ranking',label:'Ranking'},{id:'mapa',label:'Mapa de score'},{id:'detalle',label:'Detalle comuna'}])}`;}
function calcData(){const C=DATA.calc,f=F.calc;return C.data.filter(d=>!f.region||d.region===f.region);}
function bindCalc(){$('#cf-reg').onchange=e=>{F.calc.region=e.target.value;F.calc.comuna='';const coms=DATA.calc.data.filter(d=>d.region===F.calc.region).map(d=>d.comuna).sort((a,b)=>a.localeCompare(b));$('#cf-com').innerHTML='<option value="">Todas</option>'+coms.map(c=>`<option value="${c}">${c}</option>`).join('');renderTab('calc');};$('#cf-com').onchange=e=>{F.calc.comuna=e.target.value;if(e.target.value){TAB.calc='detalle';$$('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab==='calc:detalle'));}renderTab('calc');};$('#cf-reset').onclick=()=>{F.calc={region:'',comuna:''};$('#cf-reg').value='';$('#cf-com').innerHTML='<option value="">Todas</option>';renderTab('calc');};}
const scoreCol=s=>s>=70?'#EF4444':s>=50?'#F59E0B':'#16A34A';
function tabCalcRanking(){const D=[...calcData()].sort((a,b)=>b.score-a.score).slice(0,20);
  return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Ranking de comunas por oportunidad</h3><div class="subtitle">Score 0–100 · ${F.calc.region||'todo Chile'}. Mayor score = mayor oportunidad de inversión en carga.</div><div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse;font-size:13px"><thead><tr style="text-align:left;color:var(--muted);font-size:11.5px;text-transform:uppercase"><th style="padding:8px 6px">#</th><th style="padding:8px 6px">Comuna</th><th style="padding:8px 6px">Región</th><th style="padding:8px 6px;text-align:right">EVs</th><th style="padding:8px 6px;text-align:right">Conectores</th><th style="padding:8px 6px;text-align:center">DC</th><th style="padding:8px 6px;text-align:right">Score</th></tr></thead><tbody>${D.map((c,i)=>`<tr style="border-top:1px solid var(--line);cursor:pointer" data-com="${c.comuna}"><td style="padding:8px 6px;color:var(--muted)">${i+1}</td><td style="padding:8px 6px;font-weight:700">${c.comuna}</td><td style="padding:8px 6px">${c.region}</td><td style="padding:8px 6px;text-align:right">${fint(c.evs)}</td><td style="padding:8px 6px;text-align:right">${fint(c.total_carg)}</td><td style="padding:8px 6px;text-align:center">${c.has_dc?'✓':'—'}</td><td style="padding:8px 6px;text-align:right"><span style="font-weight:800;color:${scoreCol(c.score)}">${c.score}</span></td></tr>`).join('')}</tbody></table></div><div class="card-src">Fuente: análisis EV · flota + cobertura + potencial ERNC · ${DB.fecha}</div></div>`;}
function tabCalcMapa(){const D=calcData();
  setTimeout(()=>{const f=F.calc;const view=f.region&&COORDS.region[f.region]?COORDS.region[f.region]:[-35.5,-71.3];const m=leaflet('cl-map',view);if(f.region)m.setZoom(7);const pts=[];D.forEach(c=>{const co=COORDS.comuna[norm(c.comuna)]||COORDS.region[c.region];if(!co)return;pts.push(co);L.circleMarker(co,{radius:Math.max(5,c.score/8),color:scoreCol(c.score),fillColor:scoreCol(c.score),fillOpacity:.55,weight:1}).bindPopup(`<b>${c.comuna}</b><br>${c.region}<br>Score: ${c.score}<br>${fint(c.evs)} EV · ${fint(c.total_carg)} conectores`).addTo(m);});if(f.region&&pts.length){try{m.fitBounds(pts,{padding:[30,30],maxZoom:9})}catch(e){}}},60);
  return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Mapa de score de oportunidad</h3><div class="subtitle">Comunas dimensionadas y coloreadas por score · ${F.calc.region||'todo Chile'}. Ubicación aproximada al centroide comunal/regional.</div><div id="cl-map" style="height:470px;border-radius:12px;border:1px solid var(--line)"></div><div style="display:flex;gap:18px;margin-top:10px;font-size:12.5px;flex-wrap:wrap"><span class="legrow"><i class="dot" style="background:#EF4444"></i> Score alto (≥70)</span><span class="legrow"><i class="dot" style="background:#F59E0B"></i> Medio (50–69)</span><span class="legrow"><i class="dot" style="background:#16A34A"></i> Bajo (<50)</span></div><div class="card-src">Fuente: análisis EV · ${DB.fecha}</div></div>`;}
function tabCalcDetalle(){const f=F.calc;if(!f.comuna)return '<div class="card soon"><div class="big">🎯</div><h3>Selecciona una comuna</h3><p style="margin-top:6px">Elige una comuna (filtro arriba o clic en el ranking) para ver su score detallado.</p></div>';
  const c=DATA.calc.data.find(d=>d.comuna===f.comuna);if(!c)return '<p>Sin datos.</p>';const col=scoreCol(c.score);
  return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>${c.comuna} <span style="font-weight:600;color:var(--muted);font-size:14px">· ${c.region}</span></h3><div style="display:flex;gap:24px;align-items:center;margin-top:14px;flex-wrap:wrap"><div style="text-align:center"><div style="font-size:56px;font-weight:800;color:${col};line-height:1">${c.score}</div><div style="font-size:12px;color:var(--muted);font-weight:700">SCORE</div></div><div class="grid g2" style="flex:1;min-width:280px">${ind('Vehículos eléctricos',fint(c.evs))}${ind('Conectores actuales',fint(c.total_carg))}${ind('Potencia máxima',fint(c.max_kw),'kW')}${ind('¿Carga DC?',c.has_dc?'Sí':'No')}</div></div><div style="margin-top:14px;padding:12px 15px;background:${col}14;border:1px solid ${col}40;border-radius:12px;font-size:13px"><b style="color:${col}">${c.score>=70?'Oportunidad alta':c.score>=50?'Oportunidad media':'Oportunidad baja'}.</b> ${fint(c.evs)} EV y ${fint(c.total_carg)} conectores ${c.has_dc?'(con DC)':'(sin DC)'}. ${c.total_carg===0?'Comuna sin carga pública: prioridad de despliegue.':'Evaluar ampliación de capacidad.'}</div><div class="card-src">Fuente: análisis EV · ${DB.fecha}</div></div>`;}

/* ===== METODOLOGÍA ===== */
function pageMetodo(){const fuentes=[['Mercado EV','ANAC — ventas mensuales de EV/híbridos; homologaciones y fichas de seguridad','Mensual'],['Infraestructura de carga','SEC — registro de conectores públicos','Mensual'],['Energía y BESS','CEN — Coordinador Eléctrico Nacional; SEIA — proyectos','Mensual'],['Población y territorio','INE — Censo 2024','Anual'],['Tráfico vial','MOP Vialidad — TMDA','Anual'],['Permisos de circulación','Registro Civil / municipios','Anual']];
  const defs=[['Penetración EV','Participación de vehículos electrificados (BEV+PHEV+HEV+MHEV) sobre el total de ventas del mes.'],['BEV / PHEV','Eléctrico de batería / híbrido enchufable. Ambos demandan carga.'],['Conector vs cargador','Un cargador puede tener varios conectores (puntos de carga simultáneos).'],['Velocidad de carga','AC lenta ≤7 kW · AC semi 7–22 kW · DC rápida ≥50 kW.'],['ERNC','Energías Renovables No Convencionales (solar, eólica, mini-hidro, biomasa, geotérmica).'],['BESS','Battery Energy Storage System — almacenamiento en baterías (MWh).'],['Score de oportunidad','Índice 0–100 que combina flota EV, ausencia de carga, potencial de upgrade, rutas y ERNC.']];
  return `<div class="page-head"><h1>Metodología</h1><p class="sub">Definiciones y conceptos clave del observatorio.</p><div class="meta"><span class="pill">📅 Actualizado: ${DB.fecha}</span></div></div>
   <div class="card"><h3 style="padding-right:0">Definiciones clave</h3><div class="grid g2" style="margin-top:12px">${defs.map(([t,d])=>`<div style="background:#fff;border:1px solid var(--line);border-radius:12px;padding:13px 15px"><b style="font-size:13.5px;color:var(--primary-d)">${t}</b><p style="font-size:12.5px;color:var(--muted);margin-top:4px">${d}</p></div>`).join('')}</div></div>`;}

/* ===== ROUTER ===== */
const PAGES={inicio:pageInicio,resumen:pageResumen,infra:pageInfra,mercado:pageMercado,energia:pageEnergia,inversion:pageInversion,reportes:pageReportes,calc:pageCalc,censo:pageCenso,metodo:pageMetodo};
const BIND={resumen:bindResumen,infra:()=>{bindInfra();infraKpis();},mercado:()=>{bindMercado();mercKpis();},energia:()=>{bindEnergia();enerKpis();},inversion:()=>{bindInversion();invKpis();},reportes:bindReportes,calc:bindCalc};
const TABFN={
 resumen:{ind:tabResumenInd,mapa:tabResumenMapa},
 infra:{mapa:tabInfraMapa,tech:tabInfraTech,oper:tabInfraOper,evol:tabInfraEvol,dist:tabInfraDist,precios:tabInfraPrecios},
 merc:{ventas:tabMercVentas,tech:tabMercTech,marcas:tabMercMarcas,region:tabMercRegion,buscador:tabMercBuscador},
 ener:{mapa:tabEnerMapa,fuente:tabEnerFuente,region:tabEnerRegion,bess:tabEnerBess,solar:tabEnerSolar},
 inv:{mapa:tabInvMapa,cobertura:tabInvCobertura,ranking:tabInvRanking},
 rep:{ficha:tabRepFicha,mapa:tabRepMapa},
 calc:{ranking:tabCalcRanking,mapa:tabCalcMapa,detalle:tabCalcDetalle},
 censo:{viviendas:tabCensoViv,personas:tabCensoPers,mapa:tabCensoMapa}
};
function renderTab(sec){killViz();const fn=TABFN[sec]&&TABFN[sec][TAB[sec]];const panel=$('#tabpanel');if(panel&&fn)panel.innerHTML=fn();}
async function go(id){killViz();const main=$('#main');main.innerHTML='<div style="padding:60px;text-align:center;color:var(--muted)">Cargando…</div>';$$('.nav-links a').forEach(a=>a.classList.toggle('active',a.dataset.go===id));document.getElementById('navlinks').classList.remove('open');window.scrollTo(0,0);
  let html;try{html=await PAGES[id]();}catch(e){main.innerHTML='<p style="padding:40px">Error: '+e+'</p>';return;}
  main.innerHTML=`<section class="page active">${html}</section>`;
  if(BIND[id])BIND[id]();
  const SEC={mercado:'merc',energia:'ener',inversion:'inv',reportes:'rep'};
  const sk=SEC[id]||id;
  if(TABFN[sk])renderTab(sk);}
function hideInfoPop(){const ex=document.getElementById('infopop');if(ex)ex.remove();}
function showInfoPop(anchor,txt){hideInfoPop();if(!txt)return;const pop=document.createElement('div');pop.id='infopop';pop.textContent=txt;document.body.appendChild(pop);const r=anchor.getBoundingClientRect();const pw=Math.min(260,window.innerWidth-24);pop.style.width=pw+'px';let left=r.left+window.scrollX-pw+r.width;if(left<8)left=8;pop.style.left=left+'px';pop.style.top=(r.bottom+window.scrollY+8)+'px';}
document.addEventListener('scroll',hideInfoPop,true);
document.addEventListener('click',e=>{const ib=e.target.closest('.kbar-i');if(ib){e.preventDefault();e.stopPropagation();showInfoPop(ib,ib.dataset.info);return;}if(!e.target.closest('#infopop'))hideInfoPop();const tb=e.target.closest('[data-tab]');if(tb){const[s,i]=tb.dataset.tab.split(':');showTab(s,i);return;}const row=e.target.closest('tr[data-com]');if(row){F.calc.comuna=row.dataset.com;const sel=$('#cf-com');if(sel)sel.value=row.dataset.com;TAB.calc='detalle';$$('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab==='calc:detalle'));renderTab('calc');return;}const g=e.target.closest('[data-go]');if(g){e.preventDefault();go(g.dataset.go);}});
Promise.all([fetch('data/datos.json?v='+V).then(r=>r.json()),fetch('data/cargadores.json?v='+V).then(r=>r.json())]).then(([d,c])=>{DB=d;CARG=c;const ff=$('#foot-fecha');if(ff)ff.textContent='Actualizado '+d.fecha;go('inicio');}).catch(e=>{$('#main').innerHTML='<p style="padding:40px">Error cargando datos: '+e+'</p>';});

/* ===== INFRA: pestañas extra ===== */
function tabInfraEvol(){const X=DATA.infra_extra.evol;
  setTimeout(()=>{const cx=$('#if-evol');if(cx)chart(cx,{type:'line',data:{labels:X.labels,datasets:[{label:'Vehículos eléctricos',data:X.evs,borderColor:'#16A34A',backgroundColor:'rgba(22,163,74,.1)',fill:true,tension:.3,yAxisID:'y'},{label:'Conectores públicos',data:X.conect,borderColor:'#2563EB',backgroundColor:'rgba(37,99,235,.1)',fill:true,tension:.3,yAxisID:'y1'}]},options:{maintainAspectRatio:false,plugins:{legend:{position:'bottom',labels:{boxWidth:12,font:{size:11}}}},scales:{y:{position:'left',title:{display:true,text:'EVs'}},y1:{position:'right',grid:{drawOnChartArea:false},title:{display:true,text:'Conectores'}}}}});},60);
  return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Evolución de la red y la flota</h3><div class="subtitle">Vehículos eléctricos y conectores públicos por año (${X.labels[0]}–${X.labels.at(-1)}).</div><div style="position:relative;height:320px"><canvas id="if-evol"></canvas></div><div class="card-src">Fuente: SEC · ANAC · ${DB.fecha}</div></div>`;}
function tabInfraDist(){const X=DATA.infra_extra;
  setTimeout(()=>{const a=$('#if-conect');if(a)chart(a,{type:'doughnut',data:{labels:X.conectTipo.labels,datasets:[{data:X.conectTipo.vals,backgroundColor:['#2563EB','#16A34A','#F59E0B','#7C3AED','#EF4444','#0D9488','#64748B'],borderWidth:0}]},options:{cutout:'58%',plugins:{legend:{position:'right',labels:{boxWidth:11,font:{size:10}}}},maintainAspectRatio:false}});
    const b=$('#if-acdc');if(b)chart(b,{type:'bar',data:{labels:X.acdc.labels,datasets:[{label:'AC',data:X.acdc.ac,backgroundColor:'#2563EB'},{label:'DC',data:X.acdc.dc,backgroundColor:'#EF4444'}]},options:{maintainAspectRatio:false,plugins:{legend:{position:'bottom'}},scales:{x:{stacked:true,ticks:{font:{size:9}}},y:{stacked:true}}}});
    const c=$('#if-top');if(c)chart(c,{type:'bar',data:{labels:X.top.labels,datasets:[{data:X.top.vals,backgroundColor:'#2563EB'}]},options:{indexAxis:'y',maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{ticks:{font:{size:9}}}}}});},60);
  return `<div class="card" style="margin-bottom:16px"><span class="datechip">📅 ${DB.fecha}</span><h3>Conectores por tipo y por región</h3><div class="subtitle">Tipo de conector y distribución AC/DC por región.</div><div class="grid g2"><div style="position:relative;height:260px"><canvas id="if-conect"></canvas></div><div style="position:relative;height:260px"><canvas id="if-acdc"></canvas></div></div><div class="card-src">Fuente: SEC · ${DB.fecha}</div></div>
   <div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Top 20 comunas por conectores</h3><div class="subtitle">Comunas con mayor número de conectores públicos.</div><div style="position:relative;height:460px"><canvas id="if-top"></canvas></div><div class="card-src">Fuente: SEC · ${DB.fecha}</div></div>`;}

/* ===== MERCADO: pestaña Por región ===== */
function tabMercRegion(){const RY=DATA.mercado_extra.regYearly;const yrs=Object.keys(RY).sort();const last=RY[yrs.at(-1)];
  setTimeout(()=>{const cx=$('#mc-reg');if(cx)chart(cx,{type:'bar',data:{labels:last.labels,datasets:[{data:last.data||last.evs||last.vals,backgroundColor:'#16A34A'}]},options:{indexAxis:'y',maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{ticks:{font:{size:10}}}}}});
    const px=$('#mc-pen');if(px){const ps=DB.resumen.penetracion.serie;chart(px,{type:'line',data:{labels:ps.map((_,i)=>i+1),datasets:[{label:'Penetración %',data:ps,borderColor:'#2563EB',backgroundColor:'rgba(37,99,235,.1)',fill:true,tension:.3}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{display:false}}}});}},60);
  const dataArr=last.data||last.evs||last.vals||[];
  return `<div class="card" style="margin-bottom:16px"><span class="datechip">📅 ${DB.fecha}</span><h3>Vehículos eléctricos por región (${yrs.at(-1)})</h3><div class="subtitle">Flota acumulada por región.</div><div style="position:relative;height:420px"><canvas id="mc-reg"></canvas></div><div class="card-src">Fuente: ANAC · permisos de circulación · ${DB.fecha}</div></div>
   <div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Penetración EV mensual</h3><div class="subtitle">Participación de electrificados en ventas (últimos meses).</div><div style="position:relative;height:240px"><canvas id="mc-pen"></canvas></div><div class="card-src">Fuente: ANAC · ${DB.fecha}</div></div>`;}

/* ===== ENERGIA: pestañas BESS y Solar ===== */
function tabEnerBess(){const X=DATA.energia_extra;
  setTimeout(()=>{const a=$('#en-bess-anio');if(a&&X.bessAnio)chart(a,{type:'bar',data:{labels:X.bessAnio.labels,datasets:[{label:'MW',data:X.bessAnio.mw,backgroundColor:'#7C3AED'}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{ticks:{font:{size:10}}}}}});
    const b=$('#en-bess-estado');if(b)chart(b,{type:'doughnut',data:{labels:X.bessEstado.labels,datasets:[{data:X.bessEstado.mwh,backgroundColor:['#94A3B8','#F59E0B','#0EA5E9','#16A34A','#7C3AED'],borderWidth:0}]},options:{cutout:'58%',plugins:{legend:{position:'right',labels:{boxWidth:11,font:{size:10}}}},maintainAspectRatio:false}});
    const c=$('#en-bess-tech');if(c)chart(c,{type:'bar',data:{labels:X.bessTech.labels,datasets:[{data:X.bessTech.mw,backgroundColor:'#0D9488'}]},options:{indexAxis:'y',maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{ticks:{font:{size:9}}}}}});},60);
  return `<div class="card" style="margin-bottom:16px"><span class="datechip">📅 ${DB.fecha}</span><h3>Almacenamiento BESS</h3><div class="subtitle">${fint(X.bessTot.mwhAlmacenamiento)} MWh en cartera · ${fint(X.bessTot.proyectos)} proyectos. Capacidad por año de entrada y por estado.</div><div class="grid g2"><div style="position:relative;height:260px"><canvas id="en-bess-anio"></canvas></div><div style="position:relative;height:260px"><canvas id="en-bess-estado"></canvas></div></div><div class="card-src">Fuente: CEN · SEIA · ${DB.fecha}</div></div>
   <div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Capacidad total por tecnología (cartera)</h3><div class="subtitle">MW por fuente en toda la cartera (operativos + en desarrollo).</div><div style="position:relative;height:300px"><canvas id="en-bess-tech"></canvas></div><div class="card-src">Fuente: CEN · ${DB.fecha}</div></div>`;}
function tabEnerSolar(){const S=DATA.energia_extra.solar;
  setTimeout(()=>{const a=$('#en-sol-ins');if(a)chart(a,{type:'line',data:{labels:S.solarInscrita.labels,datasets:[{label:'GW inscritos',data:S.solarInscrita.solar,borderColor:'#F59E0B',backgroundColor:'rgba(245,158,11,.12)',fill:true,tension:.3}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false}}}});
    const b=$('#en-sol-anual');if(b)chart(b,{type:'bar',data:{labels:S.instalAnual.labels,datasets:[{label:'MW/año',data:S.instalAnual.solar,backgroundColor:'#F59E0B'}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{ticks:{font:{size:9}}}}}});
    const c=$('#en-sol-reg');if(c)chart(c,{type:'bar',data:{labels:S.solarRegion.labels,datasets:[{data:S.solarRegion.mw,backgroundColor:'#CA8A04'}]},options:{indexAxis:'y',maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{ticks:{font:{size:10}}}}}});},60);
  return `<div class="card" style="margin-bottom:16px"><span class="datechip">📅 ${DB.fecha}</span><h3>Energía solar — capacidad y crecimiento</h3><div class="subtitle">${fint(S.totales.mwOperativo)} MW operativos · ${fint(S.totales.proyectos)} proyectos. Top región: ${S.totales.topRegion}.</div><div class="grid g2"><div style="position:relative;height:250px"><canvas id="en-sol-ins"></canvas></div><div style="position:relative;height:250px"><canvas id="en-sol-anual"></canvas></div></div><div class="card-src">Fuente: CEN · ${DB.fecha}</div></div>
   <div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Potencia solar por región</h3><div class="subtitle">MW solares operativos por región.</div><div style="position:relative;height:320px"><canvas id="en-sol-reg"></canvas></div><div class="card-src">Fuente: CEN · ${DB.fecha}</div></div>`;}

/* ===== CENSO & ELECTROMOVILIDAD ===== */
async function pageCenso(){await Promise.all([load('censo'),load('coords').then(d=>COORDS=d)]);F.censo=F.censo||{};TAB.censo=TAB.censo||'viviendas';
  return `<div class="page-head"><h1>Censo & Electromovilidad</h1><p class="sub">Población, viviendas, licencias de conducir y potencial de carga domiciliaria por región (INE Censo 2024).</p></div>
   ${tabsNav('censo',[{id:'viviendas',label:'Viviendas'},{id:'personas',label:'Personas y licencias'},{id:'mapa',label:'Mapa por región'}])}`;}
function tabCensoViv(){const R=DATA.censo.reg;const tot=R.reduce((a,x)=>a+x.tot,0);
  setTimeout(()=>{const a=$('#cn-viv');if(a)chart(a,{type:'bar',data:{labels:R.map(x=>x.r),datasets:[{label:'Viviendas (miles)',data:R.map(x=>Math.round(x.tot/1000)),backgroundColor:'#2563EB'}]},options:{indexAxis:'y',maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{ticks:{font:{size:9}}}}}});
    const b=$('#cn-inst');if(b)chart(b,{type:'bar',data:{labels:R.map(x=>x.r),datasets:[{label:'% con instalación eléctrica adecuada',data:R.map(x=>x.inst),backgroundColor:'#16A34A'}]},options:{indexAxis:'y',maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{ticks:{font:{size:9}}},x:{max:100}}}});},60);
  return `<div class="grid g4" style="margin-bottom:16px">${ind('Viviendas totales',fint(tot))}${ind('Regiones',R.length)}${ind('% urbano (prom.)',fmt(R.reduce((a,x)=>a+x.urb,0)/R.length),'%')}${ind('% departamentos (prom.)',fmt(R.reduce((a,x)=>a+x.dpto,0)/R.length),'%')}</div>
   <div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Viviendas y potencial de carga domiciliaria</h3><div class="subtitle">Total de viviendas y porcentaje con instalación eléctrica adecuada por región.</div><div class="grid g2"><div style="position:relative;height:430px"><canvas id="cn-viv"></canvas></div><div style="position:relative;height:430px"><canvas id="cn-inst"></canvas></div></div><div class="card-src">Fuente: INE Censo 2024 · ${DB.fecha}</div></div>`;}
function tabCensoPers(){const P=DATA.censo.pers,LA=DATA.censo.licAge;const pop=P.reduce((a,x)=>a+x.pop,0);const cond=P.reduce((a,x)=>a+x.cond,0);
  setTimeout(()=>{const a=$('#cn-pop');if(a)chart(a,{type:'bar',data:{labels:P.map(x=>x.r),datasets:[{label:'Población (miles)',data:P.map(x=>Math.round(x.pop/1000)),backgroundColor:'#7C3AED'}]},options:{indexAxis:'y',maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{ticks:{font:{size:9}}}}}});
    const b=$('#cn-lic');if(b){const ks=Object.keys(LA);const lbl={a0:'<15',a15:'15-17',a18:'18-29',a30:'30-44',a45:'45-59',a60:'60+'};chart(b,{type:'bar',data:{labels:ks.map(k=>lbl[k]||k),datasets:[{label:'Tasa de licencia',data:ks.map(k=>LA[k]),backgroundColor:'#0EA5E9'}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{max:1}}}});}},60);
  return `<div class="grid g4" style="margin-bottom:16px">${ind('Población total',fint(pop))}${ind('Conductores',fint(cond))}${ind('% con licencia (prom.)',fmt(P.reduce((a,x)=>a+x.lic,0)/P.length),'%')}${ind('Regiones',P.length)}</div>
   <div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Población y licencias de conducir</h3><div class="subtitle">Población por región y tasa de licencia por grupo de edad.</div><div class="grid g2"><div style="position:relative;height:430px"><canvas id="cn-pop"></canvas></div><div style="position:relative;height:430px"><canvas id="cn-lic"></canvas></div></div><div class="card-src">Fuente: INE Censo 2024 · ${DB.fecha}</div></div>`;}
function tabCensoMapa(){F.censo.metric=F.censo.metric||'tot';const R=DATA.censo.reg;
  const metrics={tot:['Viviendas','#2563EB',x=>x.tot],inst:['% instalación eléctrica','#16A34A',x=>x.inst],urb:['% urbano','#F59E0B',x=>x.urb]};
  setTimeout(()=>{const sel=$('#cn-metric');if(sel)sel.onchange=e=>{F.censo.metric=e.target.value;renderTab('censo');};
    const m=leaflet('cn-map',[-35.5,-71.3]);const mf=metrics[F.censo.metric];const vals=R.map(mf[2]);const mx=Math.max(...vals);
    R.forEach(x=>{const co=COORDS.region[x.r];if(!co)return;const v=mf[2](x);L.circleMarker(co,{radius:8+v/mx*22,color:mf[1],fillColor:mf[1],fillOpacity:.5,weight:1.5}).bindPopup(`<b>${x.r}</b><br>Viviendas: ${fint(x.tot)}<br>% instal.: ${x.inst}<br>% urbano: ${x.urb}<br>% deptos: ${x.dpto}`).addTo(m);});},60);
  return `<div class="card"><span class="datechip">📅 ${DB.fecha}</span><h3>Mapa por región</h3><div class="subtitle">Tamaño de la burbuja según el indicador seleccionado.</div>
   <div class="filterbar" style="box-shadow:none;border:none;padding:6px 0;margin:4px 0"><div class="fgroup"><label>Indicador</label><select id="cn-metric"><option value="tot"${F.censo.metric==='tot'?' selected':''}>Viviendas totales</option><option value="inst"${F.censo.metric==='inst'?' selected':''}>% instalación eléctrica</option><option value="urb"${F.censo.metric==='urb'?' selected':''}>% urbano</option></select></div></div>
   <div id="cn-map" style="height:480px;border-radius:12px;border:1px solid var(--line)"></div><div class="card-src">Fuente: INE Censo 2024 · ${DB.fecha}</div></div>`;}
